### ISSUE TITLE
Option to show literal entry for each input method

### ISSUE THREAD

**Issue by OJFord** [mike-fabian/ibus-typing-booster#100]
It would be convenient on occasion, for example, deliberately typing 'not real' words, to have the literal entry available to select too, even if there's no dictionary match.

macOS does something a bit like this - if you select its phonetic/itrans-ish Hindi input method, the results are:
1. Best Hindi
2. Literal English (system first language, I assume) input
3. (and 4., 5., 6.) Other Hindi

**Comment by OJFord** [comment]
Oh dear, ^ I've just given away that I'm not used to this yet, haven't I... :smile:

**Comment by mike-fabian** [comment]
I think what you are looking for works already.

The literally typed text is available in the preedit, i.e. that underlined piece of text in your editor which you are just typing. The candidates which may pop up show you extensions for what you typed or spell checking corrections for what you typed or a candidate might be shown to confirm that what you typed does indeed exist in a dictionary to indicate that it is a valid word in one of your languages.

But if there is no match at all for what you typed and you want to use what you typed exactly, you can just commit the preedit. The easiest way is usually to just continue typing, for example typing a space will commit the preedit and add a space, typing a Return will commit the preedit and add a return.

Basically any key which has no special function will commit the preedit and add that key.

If you have input methods setup in the setup tool for languages which use different scripts, like English and Hindi, then the preedit shows text in the input method which has highest priority. You can change the priority in the setup tool by moving input methods up and down.

For example, if your Hindi input method is on top, the preedit will show Devanagari script, if you English input  method is on top, the preedit will show Latin Alphabet.

If you want to switch priorities of input methods fast, use these keybindings instead of the setup tool:

http://mike-fabian.github.io/ibus-typing-booster/documentation.html#key-bindings-table

Control+Down 	Bound by default to the command “next_input_method”. Switches the input method used for the preëdit to the next input method.

Control+Up 	Bound by default to the command “previous_input_method”. Switches the input method used for the preëdit to the previous input method.

For example, lets assume you type something and your preedit shows Latin Alphabet and none of the candidates which pop up are what you want (the candidates may also contain Devanagari because *all* input methods are tried to produce candidates). You want to commit the preedit, but not in Latin Alphabet, you want the Devanagari. Then type Control+Down to switch to the next input method which should be your Hindi input method if you only have two. Then the contents of the preedit will change to Devanagari and you can commit it by typing space.

**Comment by OJFord** [comment]
Thank you very much, that's a very detailed response; it does work exactly as you described, many thanks. I think what I was missing was that Ctrl-up/down works once you've already started typing too. I had found that, but didn't want to start typing मेरा नाम OJFo-- and have to delete in order to back out in order to type my username because I realise I'm on devanagari input, don't want '‍ओज्फ़ोर्द'‍, and it won't match in the English dictionary. But 'ओज्फ़ो'-- Ctrl-down -- 'rd' works great, many thanks!
