### ISSUE TITLE
[Feature Request] shortcut to disable input method temporarily

### ISSUE THREAD

**Issue by tuberry** [mike-fabian/ibus-typing-booster#111]
In Chinese input method (eg: `ibus-libpinyin`), we use <kbd>Shift_L</kbd> to toggle input mode (Pinyin and keyboard layout),  which's more convenient than switching input source by <kbd>Super</kbd>+<kbd>Space</kbd>, and it binds to a special property named [InputMode](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/status/keyboard.js#L963) in IBus and Gnome Shell. It would be appreciated to see the `InputMode` in ibus-type-booster , thanks.

**Comment by mike-fabian** [comment]
This feature already exists. It is only off by default. Start the setup tool, choose the “Key bindings“ tab and scroll down to find the command “toggle_input_mode_on_off”.

By default, this command is not bound to any key.

Bind it to any key you like (Shift_L is probably not a good choice though because it would prevent you from using the left Shift key for uppercase. If that is OK with you, you can use Shift_L to disable ibus-typing-booster temporarily, but it is probably better to use something else).

Then you have the shortcut to disable the input method temporarily.

See this screenshot:

![ibus-typing-booster-toogle-input-mode-on-off](https://user-images.githubusercontent.com/2330175/83975783-fe973e00-a8f5-11ea-8144-5112d2a36ed6.png)

**Comment by tuberry** [comment]
Thanks a lot. I missed it in the long list.
