### ISSUE TITLE
No suggestions in Firefox url and search field

### ISSUE THREAD

**Issue by ezickler** [mike-fabian/ibus-typing-booster#13]
I noticed that firefox dosen't show any suggestions if the word is still underlined which bothers me a lot as i typically find the right entries before finished typing. Some input fields dosn't seam to bother such as google. Think it's important as the hole thing is about speeding up and if the suggestion block the other i'm not sure if that speeds up anything or just confuses.

**Comment by mike-fabian** [comment]
That is interesting that it works in the Google search input field. I thought such a completion
by the application could never work because the text which is still underlined is still in “preëdit”
and not yet sent to the application. So I am surprised that this works in the Google search input field,
I never noticed this so far.

I’ll  try to find out what is different in the Google input field compared to the Firefox URL entry widget.

**Comment by mike-fabian** [comment]
In google-chrome, this even works in the URL bar:

![google-chrome-suggestions-preedit](https://cloud.githubusercontent.com/assets/2330175/23696146/b93b8fd4-03e2-11e7-8416-77123a599b0b.png)

**Comment by mike-fabian** [comment]
So it looks like google is doing something  special there in google-chrome and in
the google search page when using firefox.

Somehow google seems to be able to get the contents of the preëdit.

This behaviour is the same for *all* ibus input methods, not only ibus-typing-booster.
 I don’t think there is anything the input method can do here, firefox would need
to do something similar to what google-chrome does.

input method

**Comment by mike-fabian** [comment]
I am closing this as invalid because I  think there is nothing which  can  be done
on the side of the input method, it looks like an possible enhancement to firefox to me.

**Comment by ezickler** [comment]
cool. would be really nice if this could work everywhere.
i don't know how the preëdit works but isn't it posible to give the preëdit down to the app and change it if more input comes?

**Comment by mike-fabian** [comment]
Somehow google crome and (probably the Javascript) in the google search page are able to
access the preëdit. I have now idea how they can do this. I always thought the app doesn’t
know anything about the preëdit except its size because the app needs to reserve some space
for the preëdit. But that seems to be not true, the app seems to be able to access the preëdit somehow.

“Giving it down to the app” is basically comitting. Changing already committed stuff is quite
difficult and buggy. In apps which do not support surrounding text there is no chance 
at all for the input method to get already commited text back. Surrounding text is
currently only supported in Gtk+3 but is buggy even there.

In a Gtk+3 app, the input method can ask for the contents of the current line of text, 
delete some stuff from that line, put it back into preëdit, change it, and commit it again.

You can try that by using ibus-typing-booster for example in gedit.
Type something than walk back with Backspace or the arrow keys.
You will notice that words enter preëdit again (become underlined) when
reached with backspace or the arrow keys. 

But you might also notice that this can be quite buggy and racy when going back
with the arrow keys fast. Depending on timing and system load, this can create a complete
mess. It work only reliable when done slow. 

It is so buggy when moving fast with the arrow keys that I think I have to 
add an option whether reopening the preëdit using arrow keys should be allowed
and make that option off by default. I.e. by default only backspace will put a word back into preëdit
after I add that option and one could try to switch on support for the arrow keys
and see if it works well enough. It works well when the arrow keys are used "slow enough".
