### ISSUE TITLE
Shows password that is being entered

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#159]
Dear All,

When entering the root password in a XFCE terminal, the password that is being entered is showed.

Best regards,

Paul

**Comment by mike-fabian** [comment]
That is impossible because I think there is no way for an input method to detect a password prompt in a terminal.
That would need a working surrounding text support. Surrounding text support means that the input method is able to ask the application what text is near the current cursor position. If ibus-typing-booster could get the text to the left of the cursor position in a terminal, it could detect whether this text appears to be a password prompt. But surrounding text neither works in gnome-terminal nor in xfce4-terminal (I don't know any terminal which supports  surrounding text yet). 

Some terminals do set InputPurpose.TERMINAL when the focus enters the terminal, for example gnome-terminal and xfce4-terminal both do that. 

I have been thinking whether I could use this information that the current input goes into a terminal for something. 

Surely I could add an option to disable ibus-typing-booster in terminals which set InputPurpose.TERMINAL. Such an option might be useful for users who never want to use ibus-typing-booster in a terminal but only in other programs like editors, browsers, ...

But some users use ibus-typing-booster in terminals as well,  I also use ibus-typing-booster in terminals to complete some command lines. 

And changing the behaviour of ibus-typing-booster when input into a terminal is detected to behave better for editing command lines might be bad for users to who use editors like vim or chat programs like irssi in a terminal. These use cases are not different from typing into a graphical editor like gedit. 

But adding an option to disable ibus-typing-booster automatically in terminals might be useful for some users. Some users never use ibus-typing-booster in terminals anyway and for such users it is annoying to switch ibus-typing-booster off manually when switching to a terminal.  As a side effect this would solve the password entry problem in terminal  for users who do not want to use ibus-typing-booster in terminals.

There is also InputPurpose.PASSWORD and InputPurpose.PIN  and ibus-typing-booster already disables itself when the applications sets InputPurpose.PASSWORD or InputPurpose.PIN. But none of the terminals I know does this. There are some graphical applications which use  InputPurpose.PASSWORD or InputPurpose.PIN but no terminal so far. 

So if xfce4s-terminal could implement detecting a password prompt and then setting the content type InputPurpose.PASSWORD or InputPurpose.PIN for the input method, then ibus-typing-booster would already hide the password. 

Workarounds you could use right now and which might be useful to you:

1) There is a keybinding fo the function `toggle-hide-input` which is bound to `[Shift+Control+Escape]` by default (See the keybindings tab in the setup tool). You can change the keybinding if you prefer something else. While `Hide input` is active, ibus-typing-booster only shows an asterisk * for every character typed, does not pop-up candidate  lists, and does not record anything into its user database. This has to be done manually but with that you can hide your password input with only one key press.

2) There is a key binding for the function `toggle_input_mode_on_off`. By default this key binding is empty. You can bind this to a convenient key to switch ibus-typing-booster off temporarily. This also makes passwords hidden in terminals because when ibus-typing-booster is off, the shell will hide password input. I use 2) because I also find it convenient to disable/enable ibus-typing-booster with a single keystroke, I do that more often than switching to other input methods, therefore disabling ibus-typing-booster with a single keystroke is faster for me than to use Super+Space and switch to a keyboard layout (Super+Space is at least 2 keystrokes and possibly more if  you have many input methods setup and need to navigate to the keyboard layout).

**Comment by psads-git** [comment]
Thanks again, Mike. I think it would be a great enhancement to let the user to select in what programs to use ibus-typing-booster. For instance, ibus-typing-booster is quite annoying when searching Google, as its suggestions have precedence over Google's suggestions.

**Comment by mike-fabian** [comment]
Unfortunately the input method has no information in what program one is typing.

There are only these input purposes available:

https://developer.gnome.org/gtk3/stable/GtkEntry.html#GtkInputPurpose

GTK_INPUT_PURPOSE_FREE_FORM Allow any character
GTK_INPUT_PURPOSE_ALPHA Allow only alphabetic characters
GTK_INPUT_PURPOSE_DIGITS Allow only digits
GTK_INPUT_PURPOSE_NUMBER Edited field expects numbers 
GTK_INPUT_PURPOSE_PHONE Edited field expects phone number 
GTK_INPUT_PURPOSE_URL Edited field expects URL
GTK_INPUT_PURPOSE_EMAIL Edited field expects email address
GTK_INPUT_PURPOSE_NAME Edited field expects the name of a person
GTK_INPUT_PURPOSE_PASSWORD Like GTK_INPUT_PURPOSE_FREE_FORM , but characters are hidden
GTK_INPUT_PURPOSE_PIN | Like GTK_INPUT_PURPOSE_DIGITS , but characters are hidden
GTK_INPUT_PURPOSE_TERMINAL | Allow any character, in addition to control codes

The only one which says at least something of the application typed into is GTK_INPUT_PURPOSE_TERMINAL. At the moment, ibus-typing-booster ignores GTK_INPUT_PURPOSE_TERMINAL. I was thinking about using that somehow already, maybe adding an option to switch ibus-typing-booster off in terminals automatically. It would not work in some terminals, because not all terminals set this. For example xterm doesn't.

I don't know of any way an input method could figure out whether one is typing into Google.

> For instance, ibus-typing-booster is quite annoying when searching Google, as its suggestions have precedence over Google's suggestions.

That depends on which browser you are using.

When using firefox, you see only the suggestions from ibus-typing-booster.

When using google-chrome, you see *both* the suggestions from ibus-typing-booster *and* from Google. google-chrome seems to know about the contents of the preedit of the input method, firefox apparently not.

There are also these input hints:

https://developer.gnome.org/gtk3/stable/GtkEntry.html#GtkInputHints

ibus-typing-booster observes a few of these, for example the case related ones.

One input hint is:

GTK_INPUT_HINT_WORD_COMPLETION Suggest word completion

But that is the opposite of what I would need to disable ibus-typing-booster suggestions.
If there were some hint suggesting *no* word completion, I could switch off ibus-typing-boosters completion when such a hint is set. But there is no such hint ...

Also, very few programs seem to set input purpose and/or input hint at the moment.

I have this small test program to test how an input method reacts to input purpose and input hints. 

https://github.com/mike-fabian/ibus-typing-booster/blob/master/setup/test_input_purpose.py

which you can start like this:

```
python3 /usr/share/ibus-typing-booster/setup/test_input_purpose.py
```

and then set some input purpose and/or one or more input hints and then type
into the entries below.

You will find that ibus-typing-booster switches off when PIN or PASSWORD is set
and observes the case related hints. For example when UPPERCASE_CHARS is set, ibus-typing-booster suggests uppercase candidates by default.

Most other input hints and input purposes are ignored at the moment as I wasn't sure how to use them. The TERMINAL input purpose seems like something I could use, not sure about the others ...

Unfortunately I know of very few programs which set these at all.
Some programs seem to set PIN or PASSWORD. Some terminals set TERMINAL.
I know of no programs which set any of the other input purposes or hints except my small test program.

With my test program, you can set all of them and test how an input method would react if these hints or purposes are set.

**Comment by mike-fabian** [comment]
> For instance, ibus-typing-booster is quite annoying when searching Google, as its suggestions have precedence over Google's suggestions.

As a workaround for this, you might find the option to use different input methods for different windows useful. In Fedora 34, this option is here when using Gnome: 

![Uploading Screenshot.png…]()

**Comment by mike-fabian** [comment]
When using Gnome in Fedora 33, I think this option was somewhere else, but you will find it in the settings somewhere.

When not using Gnome this option is in ibus-setup:

![Screenshot](https://user-images.githubusercontent.com/2330175/110365534-6fb28000-8045-11eb-84be-24c7b04a910d.png)

**Comment by mike-fabian** [comment]
Using this, you can enable ibus-typing-booster only for each window separately.

I don't use that option, it confuses me too much when the input method changes automatically when focussing a different window, but maybe it helps you.

**Comment by psads-git** [comment]
Thanks again, Mike. I have just tried to unselect:

Share the same input method among all applications

but it seems it is not working fine, as I cannot activate ibus-typing-booster only on gedit.

**Comment by mike-fabian** [comment]
Is this in Gnome?

**Comment by psads-git** [comment]
No, it is on XFCE.

**Comment by mike-fabian** [comment]
It worked for me in Gnome Wayland on the Fedora 34 development version and on i3 on Fedora 33.

**Comment by psads-git** [comment]
It appears, Mike, it does not work on XFCE, Fedora 33.

**Comment by mike-fabian** [comment]
I just tried that it also works on XFCE, Fedora 34 (in a vm).

**Comment by mike-fabian** [comment]
Now I tried XFCE on Fedora 33 and you are right, using the feature to have different input methods for different windows doesn’t seem to work there. I have no idea why.

**Comment by mike-fabian** [comment]
I think I cannot do anything in ibus-typing-booster to improve this showing of the password at shell prompts in terminals.

If the terminal could somehow figure out that there is a password prompt and then set InputPurpose.PASSWORD, then ibus-typing-booster would observe that and switch itself off. This works already when InputPurpose.PASSWORD is set. 

But no terminal does that. So this could probably be fixed in terminals like xfce4-terminal and gnome-terminal.

Another possibility to fix this problem would be to fix the surrounding text support in these terminals.

Surrounding text support means that an input method like ibus-typing-booster is able to fetch the text near the current cursor positon. If ibus-typing-booster can get that text, and InputPurpose.TERMINAL is set (both xfce4s terminal  and gnome-terminal set this), then ibus-typing-booster could look at the text left to the cursor and determine whether this looks like a password prompt. 

But surrounding text support in xfce4-terminal and gnome-terminal is very broken. 

ibus-typing-booster checks whether a client claims to support surrounding text and if yes uses it, for example to get the context. It can look which words are left of the cursor then to help with the prediction of the next word.

For example in xterm, ibus-typing-booster can check that surrounding text is not supported and then just uses the last words *typed* to help predicting the next word. But that is less good because after typing these last words the cursor might have moved somewhere else and now it is in a different context. 

In gedit, ibus-typing-booster detects that surrounding text is supported and can successfully use it. There are some bugs but it works at least to some extent. In firefox as well.

Unfortunately xfce4-terminal  and gnome-terminal both indicate that they support surrounding text and therefore ibus-typing-booster tries to use it. But in reality the surrounding text support in xfce4 terminal and gnome-terminal doesn't work at all. When trying to fetch the surrounding text in these terminals, ibus-typing-booster gets the surrounding text from the previous application which is completely wrong. It is much worse to get a completly wrong surrounding then getting nothing at all.  

See this bug about the surrounding text problems in xfce4 terminal and gnome-terminal: 

https://bugzilla.redhat.com/show_bug.cgi?id=1847347

If this bug is fixed, ibus-typing-booster could try to do something to hide  the password input. 

Oŗ. if the terminals get fixed to set InputPurpose.PASSWORD when appropriate, then it would start to work in ibus-typing-booster automatically. 

But in the situation now, there is no way to fix this in any ibus input method.

**Comment by psads-git** [comment]
Thanks, Mike, for the clarification. I suppose there is a way, although not the best one:

If ibus-typing-booster can detect the window where it is being used, it can detect when the user writes 

su + ENTER

in the terminal. Thus, ibus-typing-booster would be able to detect when the root password starts to be inserted.

**Comment by mike-fabian** [comment]
No, that cannot work reliably because:

1) There is not just “su”, there are many variants like “su -”, “su - mike”, other things like “ssh -X -P 4711 mike@foobar”, scripts starting a vpn, ... there is tons of such stuff. If surrounding text doesn’t work, ibus-typing-booster cannot now where the cursor is and what else is on the line. Think about somebody using a terminal based editor like vim who writes:  
``` 
Empezó a trabajar a las 8 de la mañana. A las 5 de la tarde terminó su
 trabajo y regresó a casa en bicicleta.
```

(Spanish for “He started working at 8 am. At 5 pm he finished his work and rode home by bicycle. ”)

And then the “su” + Return causes hiding of the typing of e next line.

Without working surrounding text and being able to find out what exactly is already there and there the cursor is, there is no way to do that.

If surrounding text works, one could at least try to detect a password prompt, but even that is probably unreliable.

```
[mfabian@fedora ~]$ sudo setenforce 0 

[sudo] password for mfabian: 
```

```
[mfabian@fedora ~]$ ssh mike@localhost 
The authenticity of host 'localhost (::1)' can't be established.
ED25519 key fingerprint is SHA256:qu9YdV5GaBaFvFkXhcGgq5hUT85upEia+khKelPd7f8.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.
mike@localhost's password: 
``` 
```
sudo openvpn --config /etc/openvpn/somefile.conf
Mon Mar  8 17:39:17 2021 OpenVPN 2.4.10 x86_64-redhat-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Dec  9 2020
Mon Mar  8 17:39:17 2021 library versions: OpenSSL 1.1.1j  FIPS 16 Feb 2021, LZO 2.10
🔐 Enter Auth Username: mfabian
🔐 Enter Auth Password: **************
```
So one could try to detect a regular expression like `^.*password.*:`, i.e. try to detect whether a line starts with something followed by `password` followed by something and a `:` and the cursor is behind the colon.

But even that won’t really work.  Then somebody writes in vim in a terminal:

```
You should always use secure passwords because:
```
and then suddenly text gets hidden although this is not a password prompt.

Without surrounding text support by just remembering what has been typed recently it is completely hopeless. 

And even with working surrounding text support there would be little chance to get this right.

So I think if this can be fixed at all then by the terminal setting InputPurpose.PASSWORD at the right moment.
And I am not even sure if this is possible at all.

So there is really nothing more ibus-typing-booster can do  here than it already does. Check the input purpose whether it is PASSWORD or PIN and if yes switch itself off. If the input purpose is not set, there is not really anything useful ibus-typing-booster can do. 

Maybe try to report this to xfce4-terminal and find out whether it is possible for the terminal to set input purpose PASSWORD.

**Comment by psads-git** [comment]
Thanks, Mike. The issue is now reported to the xfce4-terminal team:

https://gitlab.xfce.org/apps/xfce4-terminal/-/issues/112

Have a nice weekend!

**Comment by mike-fabian** [comment]
> Thanks, Mike. The issue is now reported to the xfce4-terminal team:
> 
> https://gitlab.xfce.org/apps/xfce4-terminal/-/issues/112
> 
> Have a nice weekend!

Thank you, I am very interested in what they reply. I would like to understand whether or not this is possible to do for the terminal, I don’t know enough about it.

**Comment by mike-fabian** [comment]
There was no reply in https://gitlab.xfce.org/apps/xfce4-terminal/-/issues/112 and I cannot do anything in ibus-typing-booster at the moment to improve this. So I am closing this issue.

**Comment by psads-git** [comment]
Thanks, Mike!
