### ISSUE TITLE
Multi-word suggestions

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#161]
This is a suggestion to enhancing ibus-typing-booster: Make available multi-word suggestions. For example, when I write

"bes"

is quite probable that I will write 

"t regards"

afterwards.

Thus, it would improve a lot the user's typing efficiency if ibus-typing-booster suggested

"Best regards,"

as soon as I write

"bes"

and not only

"best".

Thanks, Mike!

**Comment by psads-git** [comment]
I mean something Google Docs already does. Please, see the attached screenshot.
![google_docs](https://user-images.githubusercontent.com/75945439/110673408-a8c72d80-81c8-11eb-93b1-5e05e8a3c664.png)

**Comment by mike-fabian** [comment]
That works already, see screenshot:

![Screenshot](https://user-images.githubusercontent.com/2330175/110844862-39296f00-82aa-11eb-8701-db7d18b441b4.png)

**Comment by mike-fabian** [comment]
As you can also see in the screenshot, I didn’t cheat and define “going to” or “go to” as shortcuts for go.

This works because I typed "I am going to the cinema.” first and then typed it again.

ibus-typing-booster remembers typed words in context. It remembers not only that you typed “going” but also that you typed it after “I am”. And in addition to that it also remembers pairs of words in the context of the words typed before, so it remembers that you typed “going to” after “I am” and “go to” after “going to”.

This happens automatically.

It does not remember sequences of more  than two words automatically.

But you can do that by inserting literal spaces into the preedit.

When typing  just space, the preedit gets committed. But when you type AltGr+Space, the space gets inserted into the preedit.

Like this:

![Screenshot-adding-spaces-to-the-preedit](https://user-images.githubusercontent.com/2330175/110845977-86f2a700-82ab-11eb-94ad-02762d72ad91.png)

You see that the preedit, the underlined, not committed text, contains several spaces. I inserted these  using AltGr+Space.

After doing this and typing "I am" again, I get this:

![Screenshot](https://user-images.githubusercontent.com/2330175/110846099-adb0dd80-82ab-11eb-8b8b-cf10566843e7.png)

**Comment by mike-fabian** [comment]
> I mean something Google Docs already does. Please, see the attached screenshot.
> ![google_docs](https://user-images.githubusercontent.com/75945439/110673408-a8c72d80-81c8-11eb-93b1-5e05e8a3c664.png)

By the way, the gray completion you see here in Google Docs inline. You can have this in ibus-typing-booster as well when using the option “Use inline completion”. 

The “best”, i.e. the first completion is then shown inline, if possible. “Possible” means if it just makes what you typed longer, it doesn't correct a spelling or something like that, just extends. 

Typing Tab always selects the first candidate (default key binding). That means, if a completion is shown inline, Tab selects it. If you want the second completion, just type Tab again and the full candidate list pops up. If you are happy with the inline completion selected by Tab, commit it with space.

**Comment by mike-fabian** [comment]
Looks like this:

![Screenshot](https://user-images.githubusercontent.com/2330175/110847323-15b3f380-82ad-11eb-837b-124a4fdbedff.png)

**Comment by psads-git** [comment]
Thanks, Mike. I have just written 

I am going to the cinema

four times on gedit, and never ever ibus-typing-booster suggested more than a single word per suggestion. However, after writing the same phrase a few more times, it began to suggest more than one word per suggestion. 

I missed the fact that ibus-typing-booster already have the requested feature because the elapsed learning time was not enough! 

ibus-typing-booster  is really  incredible!

**Comment by mike-fabian** [comment]
Unfortunately that is difficult to use in Wayland as Wayland cannot do colour in the preedit (at least not yet). 
In Wayland, the preedit is always one colour and always underlined. So the effect you see above where “am” is black and underlined and “ going to the cinema” is gray and not underlined is not possible in Wayland at the moment.

The inline completion feature is still usable in Wayland but hard to use as the typed part and the completion look exactly the same. One can only see the difference between the typed part and the completion by looking carefully at the cursor position. And when typing Tab the cursor jumps to the right. Hard to see, but I can get used to that after a while.

But when I am not testing something in Gnome Wayland I usually still use Xorg, so I can use that feature with nice colour.

**Comment by psads-git** [comment]
Indeed, Mike, with color, it would be better, but I can use inline completion with no problem on Fedora 33 and XFCE -- it works pretty fine.

**Comment by mike-fabian** [comment]
> Indeed, Mike, with color, it would be better, but I can use inline completion with no problem on Fedora 33 and XFCE -- it works pretty fine.

Yes, Your XFCE and my i3 windowmanager don’t use Wayland so we can still use colour in the preedit.

But it is not nice for new users who just use the default in Fedora which is Gnome Wayland and then the colour for inline completion doesn’t work.

**Comment by psads-git** [comment]
Welcome back, Mike!

I have used ibus-typing-booster extensively. However, multi-word suggestions are rare. I suspect that it is because multi-word suggestions rank in probability typically far below one-word ones. To improve ibus-typing-booster, I think it would be helpful to split the ranking of suggestions into one-word ones and multi-word ones, to make available more multi-word suggestions. What do you think, Mike?

**Comment by mike-fabian** [comment]
> I have used ibus-typing-booster extensively. 

Thank you very much!

> However, multi-word suggestions are rare. I suspect that it is because multi-word suggestions rank in probability typically far below one-word ones.

That is to be expected. If you type something like

“word1 word2 word3 word4"

the count how often you typed word3  after "word1 word2" is increased  by one. And the count how often you typed word4 after word2 and word3 is increased by one. And the count of how often you typed "word3 word4" after "word1 word2" is increased by one (Also the count that "word2 word3" has been typed after the shorter context "word1" is increased by one, the count that "word2" has been typed after "word1", etc...) 

Of course there are many more combinations of 2 words then single words,  you could type "I am going to ...", "I am going crazy ...", "I am going nuts ...", "I am going home", "I am going into ...", ...

So of course going will end up with a higher score than any of the two word combinations "going +  something".

And only the combinations which really happen incredibly often will get a high enough score to appear high enough in the suggestions. So a really, really common combination like "going to" is likely to get suggested. 

I think this is good like that because when giving the two word suggestions artificially higher weights, they would push one word suggestions which are in reality more common lower in the candidate list. 

Of course one saves typing more keys by selecting a longer candidate, so there might be some argument to give longer candidates a slightly higher weight. But not much I think pushing shorter candidates out of the limited space in the candidate lists would also be bad, then suddenly a very commonly used word might not appear anymore instead more rare suggestions would appear only because they are longer. 

It is a difficult problem to find out what is really useful. One would need statisticts to really find out whether a change is helpful or not. 

On my todo list I have for a long time already that I want to add some statistics information graphically displayed to the setup tool. Something which can show you how many keystrokes you  saved during the last day, the day before, the last week, the last month, etc. ... and more statistics like that.

If such information is displayed, one could make a change like for example increase  the count of every two word combination typed by 2 instead of one and then continue to use ibus-typing-booster a lot for a few days and see whether the number of keystrokes saved increased after the change or not.

When using SwiftKey on my Android smartphone, I also see two word combinations suggested only rarely and if they are suggested they tend to be extremely common combinations like "going to" for example.

> To improve ibus-typing-booster, I think it would be helpful to split the ranking of suggestions into one-word ones and multi-word ones, to make available more multi-word suggestions. What do you think, Mike?

I think this needs more research because such changes can easily make things worse as well.

Something I think we could try without doing much more research would be to give multi-word combinations which the user typed *consciously* into the preedit a higher weight. You know, you can add spaces into the preedit by typing AltGr+Space.

I.e. instead of typing "going" Space "to" where the space would commit the "going"  and "to" is in a new preedit, you can type "going" AltGr+Space "to" and have a preedit containing "going to". If such a preedit which contains spaces is committed, it might make sense to give it a higher weight, maybe even a *much* higher weight because the user consciously took the trouble to type this combination into the preedit. 

So it might be useful to treat committing a preedit containing a space like "going to" as if  that word combination has been typed say 10 times instead of only one time because the user must have done this on purpose.

But overall this is not easy and really needs more statistical analysis and research.

All data which is needed for the statistical analysis is already in the user database, but one really needs to look at the data after using typing-booster a lot and display the data nicely, probably best with graphics, then check whether things get better or worse when tweaks are done to the algorithm.

**Comment by psads-git** [comment]
Thanks, Mike, for your clear and detailed explanation. I agree that the analysis has to taken from a statistical point of view.

But I am afraid I was not sufficiently clear when I exposed my idea to you. What I was suggesting was to have not only one column of suggestions (as is now), but **two columns**: one for one-word suggestions and another one to multi-word suggestions. Does my idea make any sense to you?

As a side comment: Let me congratulate you, as I am really impressed by the degree of accuracy of the suggestions made by ibus-typing-booster!

**Comment by mike-fabian** [comment]
> But I am afraid I was not sufficiently clear when I exposed my idea to you. What I was suggesting was to have not only one column of suggestions (as is now), but **two columns**: one for one-word suggestions and another one to multi-word suggestions. Does my idea make any sense to you?

Two columns are not possible. The IBus lookup table has the following areas:


```
|-----------------------------|
|auxiliary text               |
|-----------------------------|
|Label | Candidate            |
|     ... more lines ...      |
|Label | Candidate            |
|-----------------------------|
|                         ↑↓  |
|-----------------------------|
```

And input method like ibus-typing-booste can fill this lookup table with content but not change its layout.

If there is nothing in "auxiliary text" (Like when you switch off the “Display total number of candidates” and  “Show status info in auxiliary text” options in typing-booster), then this area vanishes.

It is also possible to shown *only* the auxiliary text and no candidates at all.

If there are candidates, the bottom line  with the up and down arrows is there to be able to page through the pages of candidates using the mouse (*even* if there is only one page!)

But that is all that can be done with the candididate list, further customizations are not possible. 

Theoretically I could abuse the rows of the candidate list to put multiple things in each row. The candidate shown in the row does not need to be what is committed when this row is selected. This is already used for example when multiline custom expansions are displayed and the line brakes are displayed as arrows but when you commit that candidate you get the line breaks. Or, some candidates like Emoji might contain some sort of comments what kind of emoji that is and when committing only the Emoji is committed, not the comment.

So theoretically it would be possible show something like

```
|-----------------------
| 1 | going | going to |
| 2 | good | good for  |
|-----------------------
```

in rows of the candidate list. “going | going to” would be one string but only in the display, it could be different candidates internally. And it would be possible to use special key bindings to commit the first or the second part of what is displayed.

But it would not be easily possible to align the separators of the table columns vertically, this isn’t really a table, this is just text, vertical lines like | can end up in different positoins depending on fonts used for example.

But I think this is a far too complicated idea and probably not helpful. One would need different key bindings to select/commit the first or second column. And then one also needs to think about this while typing and of course read all the candidates. This would most likely slow things down more than it would help.

Even with only one column of candidates, as it is now, a huge number of candidates is not very helpful.

SwiftKey for example does a pretty good job with only 3 candidates on Android. When using SwiftKey for Japanese on Android, more than 3 candidates can be displayed, for Japanese this is necessary. But for Latin based languages only 3 candidates are possible and this is usually enough.

With ibus-typing-booster, 9 candidates are possible in the first page of the candidate list. Which is usually plenty. If you don’t see what you want there, it is usually already a waste of time to scroll down to the next page, while doing that and looking at all these candidates you would have probably finished typing what you want in full already.

I find scrolling down to the next  page only useful in rare circumstances like when I type emojis by typing something like “castle_” and get 🏰 displayed at the end of the first page of the candidate list but I want 🏯 and find it by scrolling down.

But in most cases, the really useful suggestions need to be in the first page of the candidate list, scrolling down already looses too much time.

So if "going to" is useful enough because it has appeared often enough, it should be high up in the candidate list. And if not, then not. It would not help to have a bunch of candidates in a second column which are rarely ever useful and one just looses time by looking at them to see that they are not useful.

Two word combinations are of course typically much more rare than single words.
If word1 has a 1/100 chance to appear in a text and word2 has a 1/100 chance to appear in a text *and* this chance is independent (which it usually isn’t!), the chance of "word1 word2" to appear would be 1/10000. Of course these chances are not independent, what can follow after something like "going" in the English language is far from random. Nevertheless typically two word combinations typed by the user repeat far less often than single words do and as the count is currently just increased by one both for single words and two word combinations, the two word combinations can only appear high in the candidate list if they appear really *very* often.

**Comment by psads-git** [comment]
Thanks, Mike. I have searched Google Scholar for papers on phrase prediction and found several research papers. As an example:

https://dash.harvard.edu/bitstream/handle/1/30859915/arnold16suggesting.pdf;jsessionid=8F7C37281A0906A663B814E7182E7505?sequence=1

This paper sounds promising (but I have not read yet).

**Comment by mike-fabian** [comment]
Thank you I will certainly read that.

Currently ibus-typing-booster uses an algorithm I learned from a course on coursera about natural language processing. This algorithm uses a markov chain and combines the weights of unigrams, bigrams and trigrams using a linear combination.

This algorithm is in the select_words() function in tabsqlitedb.py:

https://github.com/mike-fabian/ibus-typing-booster/blob/master/engine/tabsqlitedb.py#L447

**Comment by psads-git** [comment]
Thanks for having directed me to the python file that codes ibus-typing-booster's algorithm, Mike.

It seems that current research is focused on multi-word suggestions, according to the search I did on Google Scholar. However, I understand that ibus-typing-booster does already an excellent job -- it is most useful -- and that maintaining ibus-typing-booster is a hobby to you and not your work. So, the improvement to modern multi-word suggestions may be too much effortful and time-consuming, which may be incompatible with your work.

**Comment by mike-fabian** [comment]
Not sure, so far I didn’t yet see long multi word suggestions which were really useful. The suggestions Google’s chat program sometimes gives or  GMail didn’t really convince me. They were almost always useless for me. 

The article you found with Google scholar mostly talks about the possible user interface and not about algorithms implementing this. And how users felt trying to use this. The article cites this blog article:

https://blog.swiftkey.com/neural-networks-a-meaningful-leap-for-mobile-typing/

which seems not available anymore. I remember reading it when it was published but there was of course little information about how it would be implemented. I don’t even know whether Swiftkey ever implemented something using a neural network or whether it was just an idea.

These pages still have some screenshot, maybe from the original SwiftKey blog  entry:

https://blogs.cornell.edu/info2040/2015/10/17/neural-network-in-predictive-text-software/
https://medium.com/@curiousNupur/how-does-swiftkey-predict-your-next-keystrokes-b048ef67267d

For example the second link has a screenshot where it says that with the previous 'n-gram' model (which might be similar to what ibus-typing-booster uses, maybe), after typing "I'll meet you at the" it might offer "end", "moment", "same".

And with the new "Neural Alpha" algorithm, after typing "I'll meet you at the" it might offer "office", "airport", "hotel".

I am not  even sure whether this is clearly better, "I'll meet you at the same place as usual" would be a perfectly fine way to continue that sentence, it is not obvious that throwing out "same" in favor of "hotel" is better, it depends probably a lot on what the user typically types. 

I am using SwiftKey for a long time on Android and I never noticed a big change during the last years. I didn't notice that suddenly the suggestions became way better. Currently, when I type "I'll meet you at the" then Swiftkey gives me the suggestions "station", "airport", "moment". That of course depends heavily on my typing history, hard to tell whether the "Neural Alpha" algorithm is used currently or not.  Anyway, it doesn't seem to make a huge difference for me. 

I think I need to read more about relevant algorithms and what could be done to improve the usefulness of the suggestions.  

It is not bad already the way it is, I don’t even feel that SwiftKey is way better than ibus-typing-booster, which is surprising because they surely have a lot more resources to research this than I have. From my "feeling" (I don't have any hard data), I probably save a similar amount of keystrokes  using ibus-typing-booster than when using Swiftkey. Which is a bit surprising because the trigram algorithm ibus-typing-booster uses is quite simple. Although simple, it seems to work reasonably well.

"trigram" means it uses the last 3 words, the word you are currently typing and the previous two. As mentioned in the 

https://blogs.cornell.edu/info2040/2015/10/17/neural-network-in-predictive-text-software/

Theoretically one could use longer n-grams, i.e. consider the last 4, 5, 6, ... words. But that increases computation time a log and doesn't seem to gain much in usefulness. 

Maybe a combination of a trigram model with something else which helps tweaking the candidate list resulting from the trigram model a bit could improve something. 

But I really need to learn a lot more about this. If you find more interesting articles, just point them out to me. Maybe reading  a lot more of this stuff gives us some ideas for real improvement.

**Comment by psads-git** [comment]
Thanks, Mike, for your reply. 

From the research I did, the other algorithmic approach is based on recurrent neural network language models (RNNLMs). As you argue, the improvement gained by RNNLMs may not justify the enormous increment of complexity in comparison with the algorithm based on Markov chains that ibus-typing-booster currently uses.
