### ISSUE TITLE
Auto-capitalize appears to be causing a bug

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#167]
When one commits a multi-line shortcut, some capitalized words are not kept capitalized. Example:

```
Best regards,

Paulo
```
After committing this shortcut, `Paulo` is rendered as `paulo`.

It appears that the cause of such a problem is related to having the Auto-capitalize option active.

**Comment by mike-fabian** [comment]
Long winded explanation how it works at the moment follows and why you see this effect. After understanding the current state that we can discuss how it could be improved. 

When  ibus-typing-booster detects that one is at the beginning of a new sentence it tries to automatically capitalize. 

This detection is not perfectly reliable because surrounding text doesn't work everywhere and even where it works it doesn't work in all circumstances. So ibus-typing-booster cannot always look whether there is a full stop, an exclamation mark, or another sentence end character to the left of the cursor. Because this is a bit unreliable, ibus-typing-booster tries to be conservative and capitalize only when it is "relatively" sure that it is at the beginning of a sentence. 

For example, when typing "this is a test. " in gedit and then using any of the arrow keys or the mouse to move the cursor elsewhere, ibus-typing-booster is not sure anymore whether the cursor position is not at a sentence ending or not. 
So it doesn't do capitalizing then. 

But if you type "this is a test. " and then continue typing "test" the next  word is capitalized to "Test" because it is likely that this is a new sentence now. 

But this also could  be wrong, maybe you didn't want the capital T after all.

To fix this to get what you intended you can do:

1) Hit the shift key, possibly several times. 

   Each press of the shift key goes to the next one of the 3 states: 

  - capitalize  (first letter uppercase, all following letters lower case) 
  - upper       (all letters uppercase) 
  - lower        (all letters lowercase) 

Note that it is possible that  none of these cases includes what you originally typed. For example, if you typed "smallBig" then the "capitalize" version is "Smallbig", "upper" is "SMALLBIG", and "lower" is "smallbig".

If you just want to get what you originally typed, and none of the states toggled through with the shift key gives you this, you can type the Escape key. 

The Escape key usually discards the preedit, but if there is some change of state already the Escape key goes back to the previous state.

This also happens for example when using the emoji input feature and clicking with the right mouse on an emoji in the candidate list, related emojis are shown. The first Escape then takes you back to the original candidate list, only the second Escape discards the preedit. 

That means when you type "smallBig" and a new sentence has been detected and you see "Smallbig", the candidate list is already changed because of the autocapitalization. In that state, the first Escape goes to the "original" which is "smallBig" and the second Escape discards the candidate list.

If a candidate list is completely emptied and then typing is resumed, no autocapitalization is done.

That means if you a new sentence has been detected and you type "test" and get "Test" and didn’t want the capitalization, you can type Escape once and continue to get "test", or you could also type Escape twice and the type "test" again and it would not be capitalized again. Or you could even clear the preedit by hitting backspace four times and then type "test" again and it would not be capitalized.

The above behaviour is currently independent of whether the candidate is one word, several words, or even many lines.

That means if your candidate is "Best regards, Paul" and it is autocapitalized, it results in "Best regards, paul", which is not what we want.

As a workaround at the moment you can hit Escape to get the original candidate.

**Comment by mike-fabian** [comment]
So what can we do to improve the situation?

When I think about this, I feel like it would help to make the "capitalize" mode work only on the first word if a candidate contains several words.

Let’s say "contains several words" is defined as "contains white space".

So if the candidate is "best regards, Paul", then the "capitalize" mode should touch only the first word and make this "Best regards, Paul".

I think this would be an improvement.

**Comment by mike-fabian** [comment]
Next thing is, what should the "upper" and "lower" modes do?

Should they continue to work on the whole text? I would guess yes.

For example, if you type "best regards, Paul" and this is auto capitalized to "Best regards, Paul" and you then hit the shift key to go to the "upper" mode, it should become "BEST REGARDS, PAUL" and not "BEST regards, Paul", i.e. the "upper" mode should probably continue to work on the whole candidate.

Probably the same for the "lower" mode, if you hit the shift key again to go to lower mode, probably the complete candidate should be changed to lower case.

So my suggestion for improvement is:

Change only the behaviour of the "capitalize" mode to work only on the part of the candidate before the first white space.

What do you think, do you think this would be good?

**Comment by mike-fabian** [comment]
Slight change of my idea: 

Change only the behaviour of the "capitalize" mode to work only on the first letter of the candidate. 

Doing the capitalize only on the first letter always seems to give the same results as doing it  on the part before the first white space. When writing my last comment I was afraid there might be exceptions where working only on the first index of a string when doing the capitalization might not work in all cases, but I couldn't find any exceptions where it doesn't work.

**Comment by psads-git** [comment]
Thanks, Mike! Would it not easier to temporarily suspend "Auto-capitalize" while committing a shortcut, Mike?

**Comment by mike-fabian** [comment]
Difficulty to implement would be about the same.

I think not doing Auto-capitalization only on user shortcuts would be less good because:

- there may be two word combinations learned automatically where the second word starts with a capital letter, for example "to Japan", if this turns into "To japan" by autocapitalization this would be wrong, it should be "To Japan".
- autocapitalizaton of the first letter only may actually be useful for some user shortcuts.

**Comment by mike-fabian** [comment]
Here are test builds of ibus-typing-booster 2.11.3 for f32, f33, f34, and rawhide with the improvement to limit the "capitalize" mode to the first letter only:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/

**Comment by psads-git** [comment]
Thanks, Mike! It seems now to be working as I need. For instance, the shortcut

```
Best regards,

Paulo Sergio
```
expands correctly, that is, also `Sergio` gets capitalized.
