### ISSUE TITLE
Booster input method does not change existing keyboard layout

### ISSUE THREAD

**Issue by yoshi314** [mike-fabian/ibus-typing-booster#19]
This might be some mistake on my end, or intended behavior. 

I have Polish, German and German DE with booster setup in ibus. And i am fairly new to ibus.

German has swapped z and y compared to Polish, so this is what i noticed happen :  

- setup polish layout
- press 'z' key a few times
- 'zzzz' comes out.
- switch to German DE + booster, press z key
- 'zzz' comes out.

- switch to regular German, press z key
- 'yyyy' comes out
- switch back to German DE + booster, press z
- 'yyy' comes out

non booster layouts change the keyboard layout, the booster ones keep existing layout. This is a bit cumbersome when i type in a word with special characters, but not in dictionary yet. Perhaps i have a configuration problem somewhere?

**Comment by mike-fabian** [comment]
That is intentional. It would not be nice to force a German keyboard layout when typing
German or a French keyboard layout when typing French. 

Actually I type both German and French with a US English layout because that is what I am used
to (A slightly modified version of the US layout with some personal additions I made). I would
hate to have to type German with the German keyboard layout.

What is your preferred keyboard layout? Would you really want to switch this to something
unfamiliar? I think it is better to find a way to input the special characters while keeping
your preferred keyboard layout unchanged.

You say it is cumbersome for you to type some special characters. Which ones?

**Comment by yoshi314** [comment]
Basically the specific German characters öäüß  are tricky to type without a German keyboard layout. I quite often encounter words not on the suggestion list, even though i am not that advanced with the language.

**Comment by mike-fabian** [comment]
Have you tried using the Latin-Post input method in ibus-typing-booster?

In the setup tool for the de-DE typing booster there is a combobox labelled “Input Method:”
where you can choose between “Native Keyboard”, “Latin-Pre”, and “Latin-Post”.

If you choose either “Latin-Pre” or “Latin-Post”, the “Input Method Help” button below
will become active, clicking that gives you detailed help for these input methods.

In Latin-Pre, you can type "o to get ö, and "s to get ß.
In Latin-Post you can type o" to get ö and s/ to get ß.

You can add the direct keyboard input as a second input method by checking the
“[ ] Add direct input” checkbox.

If you have more than one input method at the same time, all input methods
are tried to match candidates.  Only one can be used for the preëdit though,
you can cycle the preëdit through the available input methods using Control+ArrowDown
or Control+ArrowUp. 

For details of using more than one input method at the same time see:

http://mike-fabian.github.io/ibus-typing-booster/documentation.html#multilingual-input

**Comment by yoshi314** [comment]
no, i have not tried that. That's interesting and might just be what i need.

**Comment by mike-fabian** [comment]
OK, please try and tell me if it does all you need.

**Comment by mike-fabian** [comment]
Did it work well enough for you purpose?

I wonder whether I should introduce an  option to enforce a certain keyboard layout when switching 
to ibus-typing-booster in future. But of course that keyboard layout would have to be configurable,
not hardcoded. At the moment I think this is not really necessary ...

**Comment by yoshi314** [comment]
I think latin-pre/post is what i need. It's just case of not RTFM on my end, or just lack of experience with ibus in general.

**Comment by Shamaoke** [comment]
> I wonder whether I should introduce an option to enforce a certain keyboard layout when switching
to ibus-typing-booster in future.

This feature is _essential_.

You can't use Booster to type Latin if you have non-Latin layout, Cyrillic, for example. When you switch to Booster from Cyrillic, you continue to type Cyrillic characters. There's no way to input Latin.

**Comment by mike-fabian** [comment]
Yes, right, there are some use cases where such a feature might be helpful and I may
implement it in future. At the moment you have to switch to a Latin layout first and
then to typing-booster if you want to type Latin.

Unconditionally enforcing some Latin layout when switching to typing-booster would be bad
as well though, not only because may different Latin layouts are available and it would be 
bad to force the use of a particular one. But also because using a cyrillic layout might 
be desired in typing booster if you want to type a language using cyrillic, using a cyrillic
layout may be more efficient than using a Latin transliteration.

So whether or not ibus-typing-booster should force a particular layout must be an option.
ibus-typing-booster should not switch to any particular layout by default.

**Comment by Shamaoke** [comment]
> At the moment you have to switch to a Latin layout first and then to typing-booster if you want to type Latin.

Suppose I  have two layouts: ru_RU and en_US-booster. I type in Russian using ru_RU and want to type in English using en_US-booster. When I switch to the last one, I'm still typing in Russian and there's no way for me to type in English.

What if I have 4 keyboard layouts:

* en_US

* ru_RU

* en_US-booster

* ru_RU-booster

When I want to switch from ru_RU to en_US-booster and then to ru_RU-booster, I have to do the following:

```
ru_RU → en_US → en_US-booster → ru_RU → ru_RU-booster
```

instead of just

```
ru_RU → en_US-booster → ru_RU-booster
```

Besides that you should do more actions, its very _confusing_ and _tiresome_ to enter text in two languages.

> But also because using a cyrillic layout might be desired in typing booster...

Exactly!

Suppose I'm an English student who's learning Russian. I type in English on a day-to-day basis. When I want to ask a question on a linguistic forum I enter the main text in English and text of examples in Russian. I need the ability to enter Russian when using two layouts: en_US and ru_RU-booster.

Please, look how it's implemented in ibus-anthy — an input method editor for Japanese. There are two input methods there: “Romaji” (Latin) and “Kana” (local alphabet). If in settings you select “Romaji” — you type Romaji, if you select "Kana" — you type Kana regardless of the layout you switched from.

**Comment by mike-fabian** [comment]
> Suppose I  have two layouts: ru_RU and en_US-booster. I type in Russian using ru_RU and want to type in English using en_US-booster. When I switch to the last one, I'm still typing in Russian and there's no way for me to type in English.
> 
> What if I have 4 keyboard layouts:
> 
> * en_US
> 
> * ru_RU
> 
> * en_US-booster
> 
> * ru_RU-booster
> 
> When I want to switch from ru_RU to en_US-booster and then to ru_RU-booster, I have to do the following:
> 
> ru_RU → en_US → en_US-booster → ru_RU → ru_RU-booster

Yes, that is the way it is at the moment.

> instead of just
> 
> ru_RU → en_US-booster → ru_RU-booster
> 
> Besides that you should do more actions, its very _confusing_ and _tiresome_ to enter text in two languages.
> 
> > But also because using a cyrillic layout might be desired in typing booster...
> 
> Exactly!
> 
> Suppose I'm an English student who's learning Russian. I type in English on a day-to-day basis. When I want to ask a question on a linguistic forum I enter the main text in English and text of examples in Russian. I need the ability to enter Russian when using two layouts: en_US and ru_RU-booster.

It is not clear whether the English student learning Russian prefers to use a russian keyboard layout.  He might prefer that, but he might also prefer to use transliteration, we don’t know, both is possible. If you look at the setup tool when using ru_RU typing booster, you see that there are several input methods available:

```
$ grep ime /usr/share/ibus-typing-booster/hunspell-tables/ru_RU.conf 
ime_name = Russian - RU (Typing Booster)
imes = Native Keyboard:NoIme,Simulated Russian Keyboard:ru-kbd,Transliteration:ru-translit,Phonetic:ru-phonetic,Yawerty:ru-yawerty
```

Transliteration, i.e. ru-translit is a transliteration input method. Select it and click the “Input Method Help” button to see how it works or look into /usr/share/m17n/ru-translit.mim.

That ru-translit input method  *requires* a keyboard layout producing Latin letters, it would not work with a cyrillic layout.

If one uses ru-RU typing booster to and ru-translit, one can type English *and* Russian without even switching to any other input method. Just check the “[✓] Add direct input” checkbox. Then a (British) English dictionary will be added in addition to the Russian completion will be tried both for the direct input (Latin letters) *and* the transliterated input (cyrillic letters).

Another way to type both English *and* Russian with the ru_RU typing booster is to use the “Simulated Russian Keyboard” i.e. “ru-kbd” input method and check the “[✓] Add direct input” checkbox. This will work well with an US English layout and several other layouts (but not well all keyboard layouts, for example a French azerty layout will not work well for this use case). Please look at /usr/share/m17n/ru-kbd.mim to see how the Russian keyboard simulation works. Again, when “[✓] Add direct input” is checked, both the Latin coming from the keyboard directly and the cyrillic which comes from the Russian keyboard simulation are tried for completion.

See http://mike-fabian.github.io/ibus-typing-booster/documentation.html#multilingual-input for more information how you can setup more than one input method (transliteration) in a single ibus-typing-booster engine and how you can load any combination of dictionaries you like in a single ibus-typing-booster engine.

So you don’t need ru_RU → en_US → en_US-booster → ru_RU → ru_RU-booster, you can stay *only* with ru_RU-booster all the time.

> Please, look how it's implemented in ibus-anthy — an input method editor for Japanese. There are two input methods there: “Romaji” (Latin) and “Kana” (local alphabet). If in settings you select “Romaji” — you type Romaji, if you select "Kana" — you type Kana regardless of the layout you switched from.

I think there is a misunderstanding here. The Japanese input methods like ibus-anthy and ibus-kkc do *not* enforce any keyboard layout, just like ibus-typing-booster they use the keyboard layout last used before switching to ibus-anthy or ibus-kkc. Just try it, use a Cyrillic layout before and switch to ibus-kkc, you will find that you cannot type Japanese, you just get Cyrillic letters. For example if you come from a US English layout and switch to ibus-anthy and type an “a”, you get an あ (Hiragana a) in hiragana mode or an “a” in the 英数 (English and digits mode) of ibus-anthy. If you come from the “ru” keyboard layout (a Cyrillic layout) and type the key at the position where the “a” is on the US layout, you will get ф not matter what input mode of ibus-anthy you choose.

This does *not* mean that ibus-anthy should enforce any particular keyboard layout. One may want to type Japanese using the US English layout, the German quertz layout, the French azerty layout, *any* layout producing the Latin letters a-z can be used to type Japanese using ibus-anthy. A user who is used to a certain layout producing Latin characters should not be prevented to type Japanese with ibus-anthy using his preferred layout.

So ibus-anthy does *not* enforce a keyboard layout for the same reason ibus-typing-booster does not.

There are some input methods like the Chinese input methods Cangjie or Wubi which *require* the use of a US English layout (Or the Chinese layout which is basically the same as the US English layout) because Cangjie is not a phonetic input method like ibus-anthy or ibus-kkc but an input method based on character shape and certain radicals are on certain keys. See: https://en.wikipedia.org/wiki/Cangjie_input_method#Keyboard_layout

But only such input methods really need to enforce a keyboard layout.

I understand that there are some circumstances where it might be useful if switching to ibus-typing-booster automatically switched to a certain keyboard layout, but this *must* be an option then, not the default. And this option should probably also offer a choice to which keyboard layout exactly it should switch to.
