### ISSUE TITLE
Showing "root" password terminal

### ISSUE THREAD

**Issue by thunderbirdtr** [mike-fabian/ibus-typing-booster#20]
I guess headline is explain itself. So basically this picture happen , either I have to switch layout before type with shortcut or is there any possible way to disable that in "su" mode ?

![password](https://cloud.githubusercontent.com/assets/1688848/23951744/ca81c47e-0997-11e7-8249-b1491ab1bf60.png)

Thank you

**Comment by mike-fabian** [comment]
ibus-typing-booster does disable itself if IBus.InputPurpose.PASSWORD or IBus.InputPurpose.PIN
is set, see:

https://github.com/mike-fabian/ibus-typing-booster/blob/master/engine/hunspell_table.py#L2514

This is set here:

https://github.com/mike-fabian/ibus-typing-booster/blob/master/engine/hunspell_table.py#L2996

But that only works if the program typed into sets this input purpose. In most Gnome programs
which ask for password input, this works.

But the shell where you type the “su” does not do that. Probably it cannot.

There is nothing ibus-typing-booster can do here, ibus-typing-booster cannot know in
what kind of program it types into and whether that program wants a password at the moment
or not. The only way is to set the input purpose and the shell doesn’t do that.
To fix that, one would need to find a way how the shell could tell gnome-terminal that
it is doing password input and gnome-terminal would then have to set the input purpose for ibus.

This is the same for *all* other ibus input methods, not only ibus-typing-booster.

I am closing this and mark it as INVALID because this cannot be fixed in an ibus input method.
