### ISSUE TITLE
Breaks unicode entry

### ISSUE THREAD

**Issue by wyqydsyq** [mike-fabian/ibus-typing-booster#28]
After installing and activating `ibus-typing-booster`, I can no longer enter characters by their unicode combinations using the Ctrl+Shift+U combination, regardless of whether I have the typing booster or default language input selected

Distro: `OpenSUSE Tumbleweed`
Kernel: `4.15.4-1`
Gnome: `3.26.1`

**Comment by mike-fabian** [comment]
I think this has nothing to do with ibus-typing-booster but with Gnome. On non-Gnome desktops this still works.

**Comment by mike-fabian** [comment]
![unicode-code-point-input-with-ibus-non-gnome-desktop](https://user-images.githubusercontent.com/2330175/37096922-739c73ce-221a-11e8-8227-e8b1808cfadd.png)

**Comment by mike-fabian** [comment]
The screenshot shows  that you can input unicode  code points on non-Gnome desktops  (XFCE in th is example) by using Control+Shift+e.

The screenshot also shows the ibus-setup tool where you can change to some other shortcut if you like.

This screenshot is taken with ibus-typing-booster-1.5.35-1.fc28.noarch installed and active.

**Comment by mike-fabian** [comment]
The dialog you see the  screenshot where you can type the code point is both for input of code points *and* emoji.  You can also type strings matching names or categories of emoji and get emoji in the same dialog.

So there used to be Control+Shift+e for the input of emoji and Control+Shift+u for the input of code points, these have been merged into one. And as Control+Shift+e is used by Gnome, you cannot use that keybinding for ibus on Gnome.

On Gnome you can start "ibus-setup" and add  another key binding, for example Control+Shift+u.

**Comment by mike-fabian** [comment]
![gnome-code-point-and-emoji-input-using-ibus](https://user-images.githubusercontent.com/2330175/37098049-2bdfffb2-221d-11e8-925d-a30a1d3939a3.png)

This screenshot shows "ibus-setup" under Gnome, where Control+Shift+u has been set as an additional keybinding to open the ibus code point and emoji input dialog. 

This has nothing to do with ibus-typing-booster, only with ibus and Gnome.

**Comment by mike-fabian** [comment]
Closing as this has nothing to do with ibus-typing-booster.

**Comment by mike-fabian** [comment]
Which versions of Gnome and ibus are you using?

**Comment by fujiwarat** [comment]
The shortcut key has been worked with non-GNOME and ibus 1.5.18 enables the shortcut key in GNOME.

**Comment by mike-fabian** [comment]
Currently I have ibus 1.5.17 in my Fedora 28 test installation:

[mfabian@Fedora-Workstation-netinst-x86_6 ~]$ rpm -q ibus
ibus-1.5.17-10.fc28.x86_64

Nevertheless with the above setup, both Control+Shift+u *and* Control+Shift+e now work for me in Gnome (Wayland) in this test installation of Fedora 28. I remember that Control+Shift+e stopped working in Gnome a while ago because Gnome was doing its own emoji input stuff on that key binding, but it looks like this has change again ...

**Comment by wyqydsyq** [comment]
```
$ rpm -q ibus; rpm -q gnome-shell
ibus-1.5.17-3.1.x86_64
gnome-shell-3.26.2+20180130.0d9c74212-1.1.x86_64
```

I'm using an X11 GNOME session rather than Wayland as I'm using the proprietary NVIDIA drivers which apparently perform poorly on Wayland currently

**Comment by fujiwarat** [comment]
ibus 1.5.17 enables `ibus emoji` command only in GNOME and you have to paste the selected string on the ibus emoji dialog.
ibus 1.5.18 enables Ctrl-Shift-e in GNOME besides `ibus emoji` but there is a problem in Xorg GNOME.
To use Ctrl-Shift-e, I'd suggest Wayland GNOME or other desktops. Otherwise I think you can use ibus-typing-booster instead.
