### ISSUE TITLE
[ENHANCEMENT] Ignore words beginning with 'x' substring

### ISSUE THREAD

**Issue by CactiChameleon9** [mike-fabian/ibus-typing-booster#340]
**Is your feature request related to a problem? Please describe.**
Passwords have shown and saved is a concern

**Describe the solution you'd like**
One solution to this is to append the beginning of your password to some sort of ignore list. I think this would be a useful feature in other situations (maybe lol)

**Describe alternatives you've considered**
I am not sure, per application whitelisting works too (ibus settings), however that completely disables this for a specific app.

**Comment by mike-fabian** [comment]
Saving even parts of passwords to some ignore list seems like a potential security issue.

If all works correctly, ibus input methods like ibus-typing-booster should be disabled on password input fields.

Some applications/toolkits disable ibus input methods on input fields completely so that the input methods don’t even get the key events anymore.

Some other applications/toolkits set hints like `InputPurpose.PASSWORD` or `InputPurpose.PIN`. If these are set on an input field, ibus-typing-booster disables itself and passes all keys through:

https://github.com/mike-fabian/ibus-typing-booster/blob/main/engine/hunspell_table.py#L5658

```python
        if (not self._input_mode
            or (self._input_purpose
                in [itb_util.InputPurpose.PASSWORD.value,
                    itb_util.InputPurpose.PIN.value])):
            return self._return_false(keyval, keycode, state)
```

**Comment by mike-fabian** [comment]
In what program are you seeing this problem? Maybe there is a problem with that program.

**Comment by CactiChameleon9** [comment]
It could also be useful to people who use speadsheets a lot and don't want auto suggestions after an = or number.

The applications were GNOME web and GNOME terminal

**Comment by mike-fabian** [comment]
> It could also be useful to people who use speadsheets a lot and don't want auto suggestions after an = or number.

> The applications were GNOME web and GNOME terminal

What is "Gnome web"? Can you be more specific and maybe add a screenshot and/or video?

**Comment by CactiChameleon9** [comment]
Sorry for the (really) late reply. Gnome web has the codename Epiphany if that helps, however I have decided that typing booster didn't work with my workflow. Feel free to re-open the issue if you think this is something worth adding
