### ISSUE TITLE
Can't use ibus-typing-booster's inline and word suggestion feature!

### ISSUE THREAD

**Issue by Mahmudul-hasan613** [mike-fabian/ibus-typing-booster#400]
**Description the bug**
Attached are two screenshots of the problem and a log file.

**Screenshots**
![2022-11-10 19-29-10 হতে স্ক্রিনশট](https://user-images.githubusercontent.com/60663471/201107858-de4f6b3f-5069-4db3-8df8-d6f3371de80b.png)

![2022-11-10 19-28-02 হতে স্ক্রিনশট](https://user-images.githubusercontent.com/60663471/201107925-9bf38814-14c4-4f2e-91fd-3fe91f4f7b73.png)

**ibus-typing-booster version ==> 2.19.8**

**ibus version ==> 1.5.26**

**Distribution and version?**
Ubuntu 22.04.1 LTS

**Desktop and version?**
Gnome 42.4

**Xorg or Wayland?**
X11

**Additional context**
[test-suite.log](https://github.com/mike-fabian/ibus-typing-booster/files/9981269/test-suite.log)

**Comment by Mahmudul-hasan613** [comment]
I found the word suggestion option. But when I type a word the word suggestion doesn't show, but if I press tab key while writing a word the word suggestion shows.

**Comment by mike-fabian** [comment]
What are your settings? You can show me your settings by doing:

```
dconf dump /org/freedesktop/ibus/engine/typing-booster/ > /tmp/ibus-typing-booster-settings.txt
```

then attach the ibus-typing-booster-settings.txt file here.

**Comment by mike-fabian** [comment]
I think the failures in the test-suite are unrelated to your problem. 

```
Error initializing Transliterator bn-inscript2 Maybe /usr/share/m17n/bn-inscript2.mim is not installed?
```
You could download https://releases.pagure.org/inscript2/inscript2-20210820.tar.gz` it contains:

```
$ tar tvf inscript2-20210820.tar.gz  | grep bn-inscript2
-rw-r--r-- parag/parag    1367 2021-05-27 08:02 inscript2/icons/bn-inscript2.png
-rw-r--r-- parag/parag    3427 2021-05-27 19:01 inscript2/IM/bn-inscript2.mim
```

and then copy `bn-inscript2.png` to `/usr/share/m17n` and `bn-inscript2.png`  to `/usr/share/m17n/icons`.

But you probably don’t need `bn-inscript2`

```
    locale.setlocale(locale.LC_CTYPE, 'am_ET.UTF-8')
  File "/usr/lib/python3.10/locale.py", line 620, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

You could install the missing locales on your Ubuntu system to avoid these fails in the test suite.


(I think I change the test suite to skip tests for specific locales if the locales are not available).

The remaining failures you see are because some hunspell dictionaries have different versions on your system compared to mine.

But I believe none of these failures in the test suite has anything to do with the problem you report.

So you can also ignore these failues if you want.

**Comment by Mahmudul-hasan613** [comment]
> What are your settings? You can show me your settings by doing:
> 
> ```
> dconf dump /org/freedesktop/ibus/engine/typing-booster/ > /tmp/ibus-typing-booster-settings.txt
> ```
> 
> then attach the ibus-typing-booster-settings.txt file here.

[ibus-typing-booster-settings.txt](https://github.com/mike-fabian/ibus-typing-booster/files/9991629/ibus-typing-booster-settings.txt)

**Comment by Mahmudul-hasan613** [comment]
> So you can also ignore these failues if you want.

Thank you so much for explaining the technical issues so nicely. And I will ignore those problems.

**Comment by mike-fabian** [comment]
> [ibus-typing-booster-settings.txt](https://github.com/mike-fabian/ibus-typing-booster/files/9991629/ibus-typing-booster-settings.txt)

Thank you!

Your settings contain:

```
inlinecompletion=0
tabenable=true
inputmethod='bn-national-jatiya,bn-unijoy,NoIME,bn-inscript2'
```

`tabenable=true` is the reason why you have to press the tab key to see completions. This option can be set to true by users who mostly don’t want completions but only want them sometimes and request them by typing tab only if they want them (It is possible to configure a diferent key than tab for this, tab is just the default).

So if you want completion always, set this option to false (I prefer false as well, false is also the default).

I.e. use this setting in the setup tool:

☐ Enable suggestions by key (Default is the Tab key)

```
inlinecompletion=0
``` 

means you have set inline `completion` to 'No'.

For inline completion there exist 3 options now:

Use inline completion :   [ No | Yes, with fallback to popup | Yes, without fallback to popup ]

“No” means you will never see the completions inline, the completions will *always* be shown as a popup.

“Yes, with fallback to popup” means the “best” completion is shown inline if possible, but if that is not possible then the completions are shown as a popup (for example because the suggested completion is not just an extension of what has  been typed but maybe a spelling correction or an emoji, or ...) If the “best” completion is shown inline but it is not what one wants, one can type Tab twice to show more completions (the first tab selects the first candidate, i.e. the “best” completioņ if one does not commit it with space but types another Tab, then the second completion is shown which forces e display of the popup).

“Yes, but without fallback to popup” also means that the “best” completion is shown inline if possible, but if that  is not possible, no popup will be shown. One can still type Tab in this case to force a popup to be shown.

**Comment by mike-fabian** [comment]
And your settings also contain `bn-inscript2`:

```
inputmethod='bn-national-jatiya,bn-unijoy,NoIME,bn-inscript2'
```

I thought you might not want it because inscript2 seems to be mostly used in India, not in Bangladesh.

But if you want it, then you can easily install it from https://releases.pagure.org/inscript2/inscript2-20210820.tar.gz

**Comment by Mahmudul-hasan613** [comment]
I understand that. Thank you so much for explaining everything so easily. Now I can see word suggestions while typing.
