### ISSUE TITLE
[ENHANCEMENT] emoji-picker: facilitate navigating by keyboard

### ISSUE THREAD

**Issue by KiaraGrouwstra** [mike-fabian/ibus-typing-booster#402]
**Is your feature request related to a problem? Please describe.**
I prefer to use a keyboard over mouse.
Using this application, I would enter a search query, then would like to select the first hit such as to copy it.
However, I haven't found a way to focus the result list without resorting to using the mouse.

**Describe the solution you'd like**
An intuitive key such as return/tab to focus the result list / first hit from the search box.

**Describe alternatives you've considered**
move my hand to the mouse :(

**Comment by mike-fabian** [comment]
I am not sure whether I understand your question correctly.

You mean a result list like in this screenshot?:

![Uploading Screenshot.png…]()

**Comment by mike-fabian** [comment]
In this screenshot, you can select the first candidate by typing 1, F1, or KP_1, the second candidate by 2, F2, or KP_2, ...

Or, you can type Tab, Down, or KP_Down to select the first candidate, another Tab to select the second, until the right candidate is selected, then commit it by typing Space. Shift+Tab, Up, or KP_Up moves up to the previous candidate. Esc cancels the selection.

The keybindings I mentioned are just the defaults, one can choose other keybindings in the setup tool:

![Screenshot](https://user-images.githubusercontent.com/2330175/203873047-51d90559-70dc-4c3d-b874-fc8d1d0e0727.png)

**Comment by mike-fabian** [comment]
Does that help or did I misunderstand the question?

**Comment by KiaraGrouwstra** [comment]
i apologize, i think i should have explained more.
the application i'm using is emoji picker, which seems to point to this repo.
looking at your screenshot tho, i'm gaining the impression that application seems related to this repo (same repo, same icon), tho the application i see in your screenshots looks distinct. i seem not to have an application called ibus-typing-booster installed.

here's a screenshot of what i was looking at, which i should have added before:
![image](https://user-images.githubusercontent.com/3059397/204009889-9c66b7ec-c9ec-4ae4-89ec-272ed469497e.png)

the keybindings there do not appear to be the same, tho i also don't see such a preferences window to configure them.

did i post this in the wrong repo perhaps?

**Comment by mike-fabian** [comment]
> i apologize, i think i should have explained more. the application i'm using is emoji picker, which seems to point to this repo. looking at your screenshot tho, i'm gaining the impression that application seems related to this repo (same repo, same icon), tho the application i see in your screenshots looks distinct. i seem not to have an application called ibus-typing-booster installed.

I think you have ibus-typing-booster installed as well because emoji-picker requires it, it uses the same emoji searching code as ibus-typing-booster. You don’t need to worry about ibus-typing-booster though if you just use emoji-picker.

Thank you for the screenshot, now I understand!

> did i post this in the wrong repo perhaps?

It is the correct repo, thank you for the report.

I am thinking what I could do.

As a long term solution, using the same key-bindings ibus-typing-booster uses to select the first candidate, the next candidate, the previous candidate, … would be good. This is not easy though, I need to do some code restructuring to achieve that. I will try.

Maybe what I can do fast without much code restructuring is to put the first match in a search into the cut buffer automaticall *always*.

I guess that would probably be “good enough” for you in most cases.

**Comment by mike-fabian** [comment]
By the way, I see you are using Japanese. Did you know that you can search in Hiragana as well?:

![Screenshot](https://user-images.githubusercontent.com/2330175/204014804-7dbac382-8c61-4b50-a208-ac2f56356e1e.png)

**Comment by mike-fabian** [comment]
See: https://mike-fabian.github.io/ibus-typing-booster/docs/user/#7_5_4`

for searching in Japanese. As mentioned there, it is useful to install pykakasi

```
pip install --user pykakasi
```

to be able to search in Hiragana (or even searching using Romaji) always if you don’t know whether the emoji names and keywords are written in Kanji or Kana.

**Comment by KiaraGrouwstra** [comment]
nice, those are pretty cool!

and glad we're on the same page again. :sweat_smile:

i agree a 20-80 here may well do. :)

**Comment by mike-fabian** [comment]
The topmost match is not automatically put into the clipboards.

I.e. you don’t need to select it with the mouse anymore, you can focus a different window (like gedit in the above video) and paste it there.

You see that the emoji has been selected and copied to the clipboards because it is also shown in the titlebar of emoji picker. This used to happen only after selecting it with the mouse.

It is of course still possible to select other than the first match with the mouse or select the first match again with the mouse, that doesn’t hurt but for the first match it is now redundant.

When selecting a match with a mouse click, one sees a small popup which says “Copied to clipboard”. This popup stays for 500 milliseconds.

When the first match is automatically selected while typing, no such popup is shown. This is because the 500 milliseconds needed to show the popup would make fast typing impossible, one would need to type slower than  one key every 500 milliseconds.

I could try to work around that by trying to show that poupup only when idle, i.e. not while keys are typed fast.

But I think that the automatically selected emoji is shown in the title bar of the window should be enough already to understand that it has been selected and put into the clipboards.

**Comment by mike-fabian** [comment]
This is included in https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.19.9

**Comment by KiaraGrouwstra** [comment]
that's great! thank you for adding this improvement! :relaxed:
