### ISSUE TITLE
[BUG] Passwords are visible while typing using ibus-typing-booster

### ISSUE THREAD

**Issue by elhananjair** [mike-fabian/ibus-typing-booster#413]
**Describe the bug**
Hello, @mike-fabian I have this problem when I type passwords on the terminal the password is visible. 

**To Reproduce**
1. Go to Konsole on kde
2. type something with sudo 
3. when you type the password is visible 

**Expected behavior**
A password should be replaced with Astrix symbol

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/69236638/215673111-40aeb219-f022-4a04-bd7e-b2b5e6db1543.png)

**ibus-typing-booster version?**
2.20.0-1

**ibus version?**
1.5.27-5

**Distribution and version?**
Fedora 37
**Desktop and version?**
KDE 

**Xorg or Wayland?**
Wayland

**Additional context**
Please feel free to add any other context about the problem here.

**Comment by mike-fabian** [comment]
This comes up again from time to time but I think there is currently no way to fix this, you just have to disable ibus-typing-booster while typing the password.

For details see:

https://github.com/mike-fabian/ibus-typing-booster/issues/159
https://gitlab.xfce.org/apps/xfce4-terminal/-/issues/112

The terminal probably doesn’t even know that a password prompt is shown and therefore probably cannot set input purpose PASSWORD. In GUI programs, the program knows whether a certain entry is a password entry or not therefore it is possible to either disable all input  methods or set input purpose PASSWORD to tell the input methods that this entry is for typing passwords. The terminal apparently cannot do that, only the program running in the terminal (sudo, ssh, ...) knows that a password is typed and tries to hide it by echoing * or nothing to terminal.

So there is nothing which can be done here except for disabling typing-booster.

Unless typing booster is used with the on-screen-keyboard (OSK), the user should be aware that typing-booster is being used and can disable it manually by switching to a plain keyboard layout or by using a key binding for quickly toggle typing booster between on and off, see:

https://mike-fabian.github.io/ibus-typing-booster/docs/user/#2_2_4 Toggle input mode on/off (Direct Input Mode)

Or, use the key binding for the command `toggle_hide_input` which is set by default to `['Shift+Control+Escape']` (which can be changed to anything you like). When hide input is active typing-booster hides the current contents of the preedit with asterisks `*` and nothing is saved to the user database.

But unfortunately this has to be done manually by the user.

When the on-screen-keyboard (OSK) is used, the user may not be aware at all that typing-booster is used because OSK enables typing booster automatically in some circumstances. Therefore, I switch off typing booster completely when the input purpose TERMINAL is set and when OSK is visible, see:

https://github.com/mike-fabian/ibus-typing-booster/issues/393

But that works only for terminals which actually do set input purpose TERMINAL, currently xfce4-terminal and gnome-terminal do that but konsole does not. And I can detect whether OSK is shown reliably only on Wayland, so this won't work on Xorg either.

Currently I am working on:

https://github.com/mike-fabian/ibus-typing-booster/issues/328  Disable input method in specific apps

When I have finished that, it will be possible to for example always disable typing booster in konsole completely. That would help if you need typing booster only in other places but not in konsole.

If you need typing booster also in konsole, then only manual disabling when password prompts are shown helps.

**Comment by elhananjair** [comment]
ok thanks, I understand.
can I ask you some maybe related questions, when I type on the firefox search bar, before using ibus-typing-booster, it suggests words or links when I start to type, but recently after starting to use ibus-typing-booster I need to enter the space key to get the suggestions from the browser.

**Comment by mike-fabian** [comment]
> ok thanks, I understand. can I ask you some maybe related questions, when I type on the firefox search bar, before using ibus-typing-booster, it suggests words or links when I start to type, but recently after starting to use ibus-typing-booster I need to enter the space key to get the suggestions from the browser.

This depends on the browser used. For example, have a look a this screenshot of google-chrome:

![Screenshot](https://user-images.githubusercontent.com/2330175/215810564-60cd5cc5-21ce-4c00-90b0-5491bed7a7e4.png)

**Comment by mike-fabian** [comment]
Here I have typed `gi` into the search field.The `gi` is underlined which indicates that it is still in “preedit”, i.e. it is still controlled by Typing Booster and not yet “committed” to the application. Firefox cannot see this “preedit” at all. If you do the same in firefox, the entry appears still to be empty to firefox and only the completions of Typing Booster are shown. 

But google-chrome apparently “sees” the contents of the preedit and uses it to show suggestions. If inline completion is not used and Typing Booster pops up a lookup table, the lookup table is usually displayed below the entry and hides part of the suggestions from google-chrome (To make this screenshot, I did put that window pretty close to the bottom of my screen which forces the Typing Booster suggestions to popup above and one can see both the Typing Booster and the google-chrome predictions at the same time.

**Comment by mike-fabian** [comment]
If one uses the inline completion mode in typing booster, often no candidate list pops up but one sees a possible completion inline. This conflicts less with the suggestions shown by google chrome. Unfortunately google-chrome cannot show different colours in the preedit, therefore the inline completion is not so easy to see, one has to carefully observe the cursor position. 

But inline completion together with google-chrome suggestions is sort of usable after getting used to it.

So if you really want to have both the suggestions of the browser **and** the suggestions of Typing Booster, try google-chrome and switch on the inline completion mode in Typing Booster. 

When using firefox, you always see the Typing Booster suggestions first until you commit, then you see the firefox completions.. 

Typing Booster cannot change that, if one thinks the behaviour of google-chrome is better one could try to implement that in firefox. 

You wrote:

> I need to enter the space key to get the suggestions from the browser.

`Space` commits the current preedit **and** adds a space. For example, if you type 

`git` and then commit with `space`, firefox gets `git ` and shows suggestions for `git` followed by a space. Which is not the same as showing suggestions for just `git` **without** a space. If you want that you can commit the preedit with a key which does not add a space, for example you can commit with the arrow right key ➡️. This commits and tries to move the cursor one position to the right but as there is no whitespace yet to the right the cursor cannot move right and thus doesn't move at all. 

Or one can commit with `Control+space` which commits and then sends a `Control+space` to the application and usually `Control+space` does not do anything (unless you are using Emacs...).

If you open the setup tool of Typing Booster and look at the keybinding settings, you will find a command 

`commit` 

which is not set to any key by default. If you set that to some key, for example set it to

`commit`   `['KP_Enter']` 

than you can commit using that key without doing anything else, i.e. not send that key to the application, just commit.

**Comment by elhananjair** [comment]
>  If you open the setup tool of Typing Booster and look at the keybinding settings, you will find a command
> 
> commit
> 
> which is not set to any key by default. If you set that to some key, for example set it to
> 
> commit ['KP_Enter']
> 
> then you can commit using that key without doing anything else, i.e. not send that key to the application, just commit.

I am on firefox and I think this one will ease up for me, I have tried it and its good

**Comment by mike-fabian** [comment]
I have test builds at https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/ (also for Fedora 37) which have a new option

☑️ Disable in terminals

**If** you never want to use typing booster in terminals (some users want to use it only in editors, browsers,....)

Then you could use that option to avoid accidentally revealing a password at a password prompt in a terminal.

I have also added another option for which I have not yet  added a UI in the setup tool but it is already usable by setting it from the command line. For example one can now  set something like this:

```
dconf write /org/freedesktop/ibus/engine/typing-booster/autosettings [['inputmode', 'false', ':.*terminal.*:']]
```

to apply some settings automatically for some programs.

In the above example, it sets `inputmode` to `false` if the client identifier ibus-typing-booster sees matches the regular expression `':.*terminal.*:`.

The client identifier is something like `toolkit:program:window-title`, for example it could be something like `gtk3-im:xfce4-terminal:Terminal - mfabian@hathi:/home/mfabian`.

I like that method better then switching off completely with 


☑️ Disable in terminals

because doing it that way, it  switches off by default in terminals but I can still enable it using a key binding if I have a keybinding set to the command `toggle_input_mode_on_off`.

Of course when switching it on in terminals using that key binding, one  has to be careful at password prompts again.

But I like it because I sometimes want to use Typing Booster in terminals but I also prefer it to be off by default in terminals.

**Comment by elhananjair** [comment]
This is a nice way to customize ibus-typing-booster and where to use it. I will check it out when the new build arrives on my Fedora.

**Comment by mike-fabian** [comment]
> This is a nice way to customize ibus-typing-booster and where to use it. I will check it out when the new build arrives on my Fedora.

2.21.0 is available for Fedora 37 now:
https://bodhi.fedoraproject.org/updates/FEDORA-2023-c98a350653

**Comment by elhananjair** [comment]
@mike-fabian thanks, this is awesome, I don't how but it arrived earlier in my case I guess:
> Package ibus-typing-booster-2.21.0-1.fc37.noarch is already installed.

**Comment by elhananjair** [comment]
Hello @mike-fabian, I don't know what am missing here but not working for me, I updated like 5 days ago I think.
![image](https://user-images.githubusercontent.com/69236638/218320756-309d7f88-2616-4268-9307-03da9187aae4.png)

**Comment by mike-fabian** [comment]
Is this Plasma Wayland?

**Comment by elhananjair** [comment]
yes

**Comment by mike-fabian** [comment]
I have tested it again on Plasma Wayland, and indeed on Plasma Wayland it does not work by default.

One has to set 

```
export QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
```

then it will work.

See the comment on top of:

https://github.com/mike-fabian/ibus-typing-booster/blob/main/engine/itb_active_window.py

```
On Wayland desktops:
    Tries AT-SPI first and falls back to xprop
...
- To make AT-SPI work with Firefox and google-chrome,
  GNOME_ACCESSIBILITY=1 needs to be set in the environment.
- To make AT-SPI work with Qt5, QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
  needs to be set in the environment
- To make AT-SPI work with Qt4, QT_ACCESSIBILITY=1 needs to be set
  in the environment
```

So I think when using Wayland, one should set all three of these environment variables in `~/.profile`.

```
export QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
export QT_ACCESSIBILITY=1
export GNOME_ACCESSIBILITY=1

```

When using Gnome Wayland, only `export GNOME_ACCESSIBILITY=1` seems to be enough because the accessibilty stuff seems always enabled in Gnome and it also seem to work fine if konsole is used on Gnome Wayland, even if `QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1` and `QT_ACCESSIBILITY=1` are not set. On Gnome Wayland, I found that detection the program name and window title failed only for firefox and google-chrome by default but setting `GNOME_ACCESSIBILITY=1` fixes it for these two browsers as well.

When using Xorg (No matter which desktop), I don't need to use the accessibilty API to get the program name and the window title, I use the `xprop` program instead to get that information. `xprop` gets me this information very reliably, but only on Xorg desktops.

On Wayland desktops, I try the accessibilty API first because `xprop` does not work for programs using Wayland. But even on Wayland, if the accessibility API does not give me a program name and window title, then I try `xprop` as a fallback. That is because if one starts Xorg programs like `xterm`, `rxvt`, `emacs`, … on Wayland, the accessibility API does not give the program name and window title but `xprop` does the job for such Xorg programs even when they are running on Wayland.

**Comment by mike-fabian** [comment]
![Screenshot](https://user-images.githubusercontent.com/2330175/218329224-41ad67e0-d32b-4a37-a57a-4ed739f822a2.png)

**Comment by mike-fabian** [comment]
Here is another screenshot where I type into the konsole at the bottom left.
This konsole has been started from the other one with:

```
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1 konsole &
```

On top of the candidate list I see now:

```
🪟 QIBusInputContext:konsole:~:bash
```

Between the first two `:` is the program name, `konsole`:

![Screenshot](https://user-images.githubusercontent.com/2330175/218329555-1d2e6751-9f24-4adb-93bd-6d7fc23e43af.png)

**Comment by mike-fabian** [comment]
For non-Gtk based terminals, like konsole, I need the program name to detect it, see:

https://github.com/mike-fabian/ibus-typing-booster/blob/main/engine/itb_util.py#L2272

```python
@functools.lru_cache(maxsize=None)
def detect_terminal(input_purpose: int, im_client: str) -> bool:
    '''Detect whether the focus is on a terminal
    Checks input purpose first and if that is not set to TERMINAL,
    checks the program name in im_client to guess whether it is
    a terminal.
    '''
    if input_purpose in [InputPurpose.TERMINAL.value]:
        return True
    if not im_client:
        return False
    terminal_regexps = [
        '^xim:xterm:',
        '^QIBusInputContext:konsole:',
        '^xim:rxvt:',
        '^xim:urxvt:',
    ]
    for regexp in terminal_regexps:
        if re.compile(regexp).search(im_client):
            return True
    return False
```

The Gtk based terminals `gnome-terminal`, `gnome-console`, `xfce4-terminal` set input purpose to TERMINAL, so for these terminals disabling Typing Booster should always work, even when neither the accessibility API nor `xprop` are available.

But if input purpose TERMINAL is not set, I try to match on the toolkit and window title. Currently I try to match only 4 terminals:

```
        '^xim:xterm:',
        '^QIBusInputContext:konsole:',
        '^xim:rxvt:',
        '^xim:urxvt:',
```

It matches on the string you see when debug is on above the candidate list. So for konsole, it tries to match on `^QIBusInputContext:konsole:`.

And on Plasma Wayland this unfortunately needs the accessibility API.

So please set

```
export QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
export QT_ACCESSIBILITY=1
export GNOME_ACCESSIBILITY=1
```

in your `~/.profile` and log in again, then it should start to work.

**Comment by elhananjair** [comment]
@mike-fabian wow thank you for such a brief description after I set the ENV VAR it worked on konsole. Thank you so much for investing your time in this project.

**Comment by elhananjair** [comment]
@mike-fabian Wow, this issue keeps coming, I am on Fedora 38 now and have followed the instruction you gave last time, but no luck. 

![image](https://github.com/mike-fabian/ibus-typing-booster/assets/69236638/eca45972-e7f2-40aa-82c5-0029f3a5c5ad)
