### ISSUE TITLE
[ENHANCEMENT] Multi-word suggestions disappear with space

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#437]
Hi, Mike, 

Suppose `ibus-typing-booster` suggests 

`Palace of Buckingham`

We write 

`Palace`

and the multi-word suggestion `Palace of Buckingham` appears , but, as soon as we hit `space`, the multi-word suggestion vanishes. Maybe it would be more useful to keep the multi-word suggestions active. What do you think about that?

**Comment by mike-fabian** [comment]
I am not sure I understand. 

You could have accepted the whole suggestion `Palace of Buckingham` by typing `Tab` after typing `Palace`. If you type `space` instead of `Tab`, that means you did *not* want to use that suggestion, just `Palace`. So why would it be useful to keep `of Buckingham` around?

**Comment by mike-fabian** [comment]
Unrelated side remark: a while ago I introduced a workaround for you to make multiline shortcuts work in the GMail editor of firefox, the workaround commits each line separately and uses `forward_key_event()` to forward a `Return` in between to get the newlines. This causes problems on Wayland though, as `forward_key_event()` is quite buggy on Wayland. See:

https://github.com/mike-fabian/ibus-typing-booster/issues/438

As this workaround was only needed for firefox (actually only for the GMail editor in firefox) and thunderbird, I have now changed the code to apply that workaround only when the client id matches `^gtk3-im:(firefox|thunderbird)` if that does not match I commit the  whole multiline shortcut at once. That works equally well on Xorg in most cases it is OK to commit the whole string at once, only firefox and thunderbird seem to need that work around (actualy even in firefox it mostly works without that workaround, only the GMail editor in Firefox seems to need it, I am wondering whether I should restrict the regepx when to apply the workaround even more ...). 

Changing to commit multiline shortcuts with one single commit makes it work well in Wayland except for firefox and thunderbird, in firefox and thunderbird on Wayland neither method works, committing each line separately and using `forward_key_event()` for `Return` causes many extra repetitions of `Return` and when committing at once the GMail editor in firefox swallows the new lines. So I would recommend to use Xorg if one wants this to work. Or, if one wants to use Wayland, then start firefox like `GTK_IM_MDOULE=ibus firefox` to avoid using the Wayland input on firefox.

I hope that after my change for https://github.com/mike-fabian/ibus-typing-booster/issues/438 it still works equally good for your use cases as before, if you notice any regression, please tell me.

**Comment by psads-git** [comment]
> I am not sure I understand.
> 
> You could have accepted the whole suggestion `Palace of Buckingham` by typing `Tab` after typing `Palace`. If you type `space` instead of `Tab`, that means you did _not_ want to use that suggestion, just `Palace`. So why would it be useful to keep `of Buckingham` around?

While typing, Mike, it is a human automatism to finish a word with hitting `space`. So, the `space` does _not_ mean, necessarily, one does not want to use the suggestion!

**Comment by psads-git** [comment]
> I hope that after my change for #438 it still works equally good for your use cases as before, if you notice any regression, please tell me.

I will inform you, Mike, if I notice any regression. Thanks for keeping me informed about the improvements you have added to ibus-typing-booster!

**Comment by mike-fabian** [comment]
Doesn't this already do what  you want?:

https://user-images.githubusercontent.com/2330175/232424070-c5961917-9cf6-4904-aee1-4af1a53b17f1.mp4

Note that I did set `Minimum characters for completion` to 0.

Setting this to 0 makes it possible to get high quality completion even if typing of the next word has not started yet.
That feature is available since https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.20.0, before that `Minimu;m characters for completion` had to be >= 1.

See also this comment for another video showing that feature:

https://github.com/mike-fabian/ibus-typing-booster/issues/268#issuecomment-1385108314

**Comment by psads-git** [comment]
If that produces bad prediction, the best is to leave as it is, Mike. And maybe we can close this enhancement request.

**Comment by mike-fabian** [comment]
OK, let’s leave it as it is for the moment until we have a better idea.
