### ISSUE TITLE
Accept first suggestion by default.

### ISSUE THREAD

**Issue by kevincox** [mike-fabian/ibus-typing-booster#44]
It would be nice if there was a mode to accept the first suggestion by default. This is because I am usually typing words in my dictionary (or learned words) so I would like it if my minor typos were corrected. This is how most mobile keyboards work so I think many people would like the behavior.

In order for this to work however there would also need to be a way to accept the typed word without any correction being applied.

**Comment by mike-fabian** [comment]
Can you give some  examples of this? I am trying to understand 
what you mean exactly.

**Comment by mike-fabian** [comment]
What mobile keyboard are  you talking of in particular, what behaviour exactly do you like and find useful?

**Comment by kevincox** [comment]
For example if I type `neibhor<Space>` I would like for it to insert neighbor instead as that would be the first suggestion. For example GBoard and IIRC the default iOS keyboard work like this.

**Comment by mike-fabian** [comment]
On the virtual keyboards on Android I usually switch that option of,
if possible.  It annoys me a lot to get such automatic
corrections. Too often they are not what I want.  Even though the
prediction quality of my favorite virtual keyboard on Android is a
little bit better than the current prediction quality of
ibus-typing-booster, it still is not good enough for me to find
autocorrection useful. So I always switch that off.

But that may depend quite a bit on taste and on what language one uses
(Some languages have better hunspell dictionaries than others for
example).

But I think adding that as an extra option which is off by default
might be OK.

So I have added such and option. I am using it at the moment while
writing this and it already annoys me.. It might be useful but one the
user also needs to get used to the different behaviour. One can save
the keystroke to type Tab to select the first candidate every time the
first candidate is perfectly what one wants. One the other hand one
has to use an extra keystroke (Escape, which is the default key
binding for the 'cancel' command) to deselect that first candidate if
none of the candidates is what  one wants and one really wants to
insert *exactly* what one has typed instead of any of the candidates.

So whether switching this option on can save you keystrokes or not
depends on how often the first suggestion (or any of the following
candidates) is better than what you typed and how often what you typed
is better than any of the candidates.

Either way, using this option changes the way one has to use the
Tab and the Escape key considerabely, so it takes some time to get
used to it. Therefore, I don’t want to make it the default.

I’ll probably add  this option in the next release.

**Comment by mike-fabian** [comment]
If you want to  test that option now you can try this branch: 
https://github.com/mike-fabian/ibus-typing-booster/tree/release-2.5.1

This commit adds this option: 
https://github.com/mike-fabian/ibus-typing-booster/commit/397850b67ecd3673b28340fec59994ed2b749d50

**Comment by mike-fabian** [comment]
The option is in the 2.5.1 release now: 
https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.5.1

**Comment by kevincox** [comment]
Sorry for the delay. It have just had time to test this out and it is great. It fixes small typos with no additional effort. Thanks!

**Comment by mike-fabian** [comment]
Did you test 2.6.0 already?

In 2.6.0, I added  this feature:

- If an input char is typed while a candidate is *manually* selected, add that input to the candidate

For example if you type "ho" and the  first  candiate is  "house" and you select  it by typing Tab and  then type "s", the "s" is added to the  selected candidate, i.e. you have "houses" in the preedit then. That is very nice and useful if the candidate is *manually* selected,  because then  you really wanted "house" and probably wanted to add  the "s" at  the end. 

But if the option "Automatically select the best  candidate" is on, this new behaviour does not  make sense, if a candidate was automatically selected, it is much more likely that  you want  to continue to add input to the preedit instead of adding  it to the selected candidate.

So I  use this new, improved behaviour of adding input to selected candidates *only* if the candidate has  been selected *manually*, not if it has been selected *automatically*. 

I.e.  if you use the option “Automatically select the best  candidate”, the behaviour for you should *not* have changed between version 2.5.3 and 2.6.0 if I did it right.
