### ISSUE TITLE
[ENHANCEMENT] Case-insensitive shortcuts

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#443]
Hi, Mike,

I have just noticed that, for instance, for the shortcut

`London`

when writing 

`l` 

(notice the `L` in lower case),

the suggestion of the shortcut is not triggered, whereas with typing

`L`

the shortcut is suggested.

Maybe lower case typing should trigger the shortcut suggestion. What do think about that?

**Comment by psads-git** [comment]
Thanks, Mike, for your answer. I am sorry for I was not very clear: I mean not the shortcut that triggers the expansion, but the expansion itself. 

Suppose we have the shortcut

`lo`

that expands to

`London`

If we type `L`, we immediately get `London` as inline autocomplete suggestion, but not when we type `l` (lowercase `L`).

**Comment by mike-fabian** [comment]
If yo type `l` you cannot get London as an inline completion because completions are never shown inline when the completion would change anything you typed already. In this case, the lower case `l` would need to change to uppercase `L`, therefore no inline completion can be shown. Inline completions which do not just make what you typed longer but change something you already typed would be far to confusing.

As you can see in the video below, `l` *does* trigger the shortcut `London`, only it cannot be shown inline.

That means if you option to shown inline completions is "Yes. without fallback to popup”, then `London` is not shown immediatelyi but it is shown when you type `Tab` to force showning the candidate list.

My preferred setting for inline completions is “Yes, with fallback to candidate list”. Using that, typing `l` shows the shortcut `London` immediately, not inline but as the first candidate of the candidate list which pops up. I think this is better because it makes it clear that this might be more than just an extension of what you typed.

User defined shortcuts are case sensitive. Therefore, `L` does *not* trigger the shortcut expansion `lo` ➡️  `London`.

The reason why you see `London` as an inline completion when typing `L` is that the word `London` is in the English dictionary *and* probably also in the database of the words you typed before.

In the video you can clearly see that, I did set the debug level to 3 and switched off inline completion at the end of the video to always show show a candidate list and to show the weights calculated for the candidates. When typing l, I can see the candidate `London 1000000`. This shows that it was a shortcut expansion because shortcut expansions have weights >= 1000000. “Normal” completions always have weights between 0 and 1. When typing `L` I get the first candidate `London 0.99…` which shows that this is *not* a shortcut expansion but a “normal” completion with close to the maximum weight.

https://github.com/mike-fabian/ibus-typing-booster/assets/2330175/6e320fc1-58c8-47ca-9544-8cde14f518f3

**Comment by psads-git** [comment]
> Inline completions which do not just make what you typed longer but change something you already typed would be far to confusing.

True, Mike. But the inline completion does not need to use the previously typed characters as part of the completion. For instance, suppose one types

`l`

the completion would be added to the `l` 

`lLondon` 

(notice the first `l` would not be replaced by capital `L`) and that would be converted to 

`London` 

_only_ after committing the completion.

I am not sure whether this change is worthy the effort to implement it, Mike!

**Comment by mike-fabian** [comment]
No, I don’t think this makes sense. This would not be inline *completion* but showing a *full* candidate inline behind what you typed. That would be very confusing in practice.

**Comment by psads-git** [comment]
I understand, Mike. Thanks!

Since I do not have any other idea that might improve the inline completion of capitalized shortcuts, I would suggest to close this enhancement ticket.

**Comment by mike-fabian** [comment]
OK, I’ll close one.

But feel free to report more stuff, your reports are always useful. Even though I am closing this one now without having done any change to the code, it was good to think about it.
