### ISSUE TITLE
Compose sequences don’t work in ibus-typing-booster (was: Can this be built on Mint 19 Cinnamon?)

### ISSUE THREAD

**Issue by Salvatos** [mike-fabian/ibus-typing-booster#47]
Hi! I'm sorry to bother you with this but I have been trying desperately to build this from source on Mint 19 Cinnamon to no avail. I added, removed and changed libraries up to the point where `make` didn't return any errors, had to mess with DBus but seem to have it installed and running now, tried the instructions here and those on other sites, but I still don't have any "other" or "booster" entries in the language input settings. I am at a loss for what else to try.

If you could provide step-by-step instructions to get it to work on this system (or get a new PPA up and running?), I would be more than happy to make a donation for your time.

Edit: I finally found some more missing libraries and now have those options, but turning on Typing Booster as an input method doesn't result in any suggestions in any program I've tried...

**Comment by Salvatos** [comment]
After installing the Gnome desktop and messing around with it a bit, ibus-typing-booster seems to now work both in Gnome and Cinammon. However my keyboard layout (French Canadian) doesn't seem to be supported. Accented characters aren't showing up when I use IBT as input method and I don't see FRCA in the list that can be added. Should I open a different issue?

**Comment by mike-fabian** [comment]
I just tried it with Cinnamon on Fedora 29 and it worked. So I don’t have to try on Mint
as well I guess, because it now works for you, right?

**Comment by mike-fabian** [comment]
Maybe better a different issue for the keyboard problem.

**Comment by mike-fabian** [comment]
I am trying to explain your keyboard problem here:

I guess there is no bug, just a misunderstanding. You don’t add keyboard layouts in the setup tool of ibus-typing-booster. You only add dictionaries and input-methods. See this part of the documentation:

http://mike-fabian.github.io/ibus-typing-booster/documentation.html#multilingual-input

You might want a setup like this:

![ibus-typing-booster-setup-for-canadian-french-and-english](https://user-images.githubusercontent.com/2330175/52712277-618ff380-2f94-11e9-8011-688a82473c62.png)

Here I added the fr_CA dictionary (French in Canada) and the en_CA dictionary (English in Canada).
This might be helpful if you want to type both French and English. If you only need French, then don’t add the English dictionary, the prediction quality suffers if you add more dictionaries than you really need and ibus-typing-booster also gets slower when you use more dictionaries at the same time.

I added 2 input methods:

NoIME (Native Keyboard)
t-latn-post (Latin Post)

Latin Post is completely optional, if you add that you can type accented letters using a postfix notation,
i.e. you could type garc,on and get garçon (Select the input method in the setup tool and click the "Input Method Help" button to see how Latin Post works). Probably you don't want that, in that case use 
only 

NoIME (Native Keyboard)

This dummy input method (NoIME means "No Input Method") means that it just uses whatever comes from your keyboard layout and does not change the input at all (Latin Post changes c, into ç). 


You have to setup your preferred keyboard layout *outside* of ibus-typing-booster booster.
In case of Gnome, you do that in the Gnome control center. Looks like this: 

![screenshot](https://user-images.githubusercontent.com/2330175/52712615-70c37100-2f95-11e9-91db-9db1ce4f560d.png)

Select your preferred French Canadian keyboard  layout there. 

ibus-typing-booster uses whatever keyboard layout was used last before switching to 
ibus-typing-booster: If you have only two input methods configured in Gnome, the French Canadian keyboard layout and ibus-typing-booster, then ibus-typing-booster will use the French Canadian layout.

Let’s assume you have another keyboard layout configured in gnome and see something like this in the Gnome-panel: 

English (US, euro on 5)     en
Canadian Multilingual      fr 
Other (typing-booster)    🚀 

In that case, if you first click on "en" and then  "🚀", ibus-typing-booster will use the US English layout.
If you first click on "fr" and then "🚀", then ibus-typing-booster will use the Canadian French layout.

**Comment by mike-fabian** [comment]
Does that solve your problem with the French Canadian keyboard layout?

**Comment by Salvatos** [comment]
Hi Mike and thanks for the thorough answer. My settings are pretty much like you describe: English and French dictionaries, NoIme input method, and input sources FR-CA and IBT only. I uploaded screenshots here: https://imgur.com/a/j8cN2lx

The problem appears to be specific to combination keys. For instance I have an É key right on the keyboard, and that works. But I have to type ^ followed by O to get Ô, and when IBT is on that only gives me an O; same with other accents and letters. The accent key is just ignored. I included a short video in the gallery above to demonstrate. As a sidenote, the accent keys do seem to be completely turned off. I would normally press ^ twice to get ^ on its own or ` twice for a backtick, for example, and with IBT on nothing shows up.

To answer your earlier questions about it working on Mint+Cinnamon, I'd say partially. I have a bug where the suggestion window goes so low on the screen I can barely see the first entry, so it's largely unusable. It seems to happen with maximized windows specifically. On smaller ones it appears under the window or in the bottom left corner of the screen but within bounds, sometimes alternating between those locations.

And ever since I installed Gnome packages I am getting XKB errors that probably don't have anything to do with IBT but make me wish I could use IBT without those packages. Specifically, every time I boot into a new session, return from sleep or plug in a USB device I get a warning telling me there was an error activating XKB's configuration. When I return from sleep, I actually get 5+ of those pop-ups. I haven't noticed anything actually wrong with my keyboard input though, besides accented characters with IBT.

**Comment by mike-fabian** [comment]
> Hi Mike and thanks for the thorough answer. My settings are pretty much like you describe: English and French dictionaries, NoIme input method, and input sources FR-CA and IBT only. I uploaded screenshots here: https://imgur.com/a/j8cN2lx

OK, the screenshots look good.

> The problem appears to be specific to combination keys. For instance I have an É key right on the keyboard, and that works. But I have to type ^ followed by O to get Ô, and when IBT is on that only gives me an O; same with other accents and letters. The accent key is just ignored. I included a short video in the gallery above to demonstrate. As a sidenote, the accent keys do seem to be completely turned off. I would normally press ^ twice to get ^ on its own or ` twice for a backtick, for example, and with IBT on nothing shows up.

Ah, this is the problem that all compose sequences don’t work. Your
keyboard layout has “dead keys”, i.e. keys like ^ which first don’t
output anything at all but only output something when some other key
is pressed after such a key. “dead keys” are a special type of compose
sequence. This has been reported before, see:

https://github.com/mike-fabian/ibus-typing-booster/issues/36

I will work on fixing this, but this is not easy at all and will take considerable time.
I will make this high priority to fix this now.

As a workaround for the meantime, you could try whether using some
French keyboard layout which does not use dead keys works reasonably
for you. There is the “French (no dead keys)” keyboard offered in
Gnome, you could try to add that one in addition to your “French
(Canadian)” layout and before switching to ibus-typing-booster first
switch to “French (no dead keys)” and then to ibus-typing-booster
(because ibus-typing-booster uses the currently active layout).

And/or maybe try out adding either the Latin Prefix or Latin Postfix input method
in ibus-typing-booster. I thought you don’t need these because you use a French layout
already, but as it is a French layout using dead keys, this is a problem because
dead key support is not implemented yet in ibus-typing-booster.

Personally, I mostly use Latin Postfix to type accented characters,
with Latin Postfix I type a^ to get â (With Latin Prefix one would
type ^a to get â, that is quite similar to using a layout with dead
keys).

I really should add dead key support to ibus-typing-booster as soon as possible ...

> To answer your earlier questions about it working on Mint+Cinnamon, I'd say partially. I have a bug where the suggestion window goes so low on the screen I can barely see the first entry, so it's largely unusable. It seems to happen with maximized windows specifically. On smaller ones it appears under the window or in the bottom left corner of the screen but within bounds, sometimes alternating between those locations.

That is not specific to ibus-typing-booster, it happens with *all*
ibus input methods.  The same thing can happen if you for example use
ibus-kkc or ibus-anthy to type Japanese or ibus-libpinyin to type
Chinese. None of these ibus input methods can draw this suggestion
window, ibus core draws this window. The individual input methods just
supply the contents for the suggestion window and then ibus draws it.

> And ever since I installed Gnome packages I am getting XKB errors that probably don't have anything to do with IBT but make me wish I could use IBT without those packages. Specifically, every time I boot into a new session, return from sleep or plug in a USB device I get a warning telling me there was an error activating XKB's configuration. When I return from sleep, I actually get 5+ of those pop-ups. I haven't noticed anything actually wrong with my keyboard input though, besides accented characters with IBT. (I don't get those warnings when I launch a Gnome session.)

I don’t know about these things. 

> Edit: Oh and if I try to type a program name in the Applications menu while IBT is on, IBT kind of captures the output and the menu doesn't suggest any program although the characters I'm typing appear in the search field. I'm not sure that is specific to Cinnamon, though, it seems like it could be a common problem.

Yes, that is also a problem with *all* input methods, not just ibus-typing-booster.

When you type with any input method, the text you type is first in
something called “preedit”. This means the text is still in the input
method and not in the application.  In many cases you can see that
because the text is underlined or otherwise somehow differently
styled. In ibus-typing-booster you can choose the style for the
preedit, it is also possible to choose no styling at all, but the
default is a single underline.  With no styling at all for the
preedit, you would not see that it is a preedit, but it would still be
the same behaviour. The application you are typing into usually knows
what is in the preedit, it needs this information to calculate how
much space is needed to display the preedit and maybe move the stuff
to the right of the preedit further right if you insert text.
But most applications use this information only to calculate the available
space, not to do suggestions.

Some do though: For example, if you use ibus-typing-booster to type
into the URL bar of the google-chrome browser, you see that
google-chrome offers you suggestions based on your browsing history
even when your typed text is still in preedit (underlined) and you did
not yet type space to "commit" it ("commit" means inserting the
contents of the current preedit into the application). If you do the
same thing with firefox, firefox does *not* offer any suggestions
based on your browsing history until you commit the preedit (for
example by typing a space).

This is the same in the search field in Gnome or Cinnamon, these
search fields use the contents of the preedit only to calculate the
space needed to display the preedit, but they don’t use the content of
the preedit to show some suggestions.

So I think this is a missing feature in Firefox, Gnome, and Cinnamon,
not in the ibus input methods. Firefox, Gnome, and Cinnamon should
use the contents of the preedit already to start a search for suggestions,
not wait for the commit.

**Comment by Salvatos** [comment]
> As a workaround for the meantime, you could try whether using some French keyboard layout which does not use dead keys works reasonably for you.

Unfortunately, all of those layouts are in AZERTY or QWERTZ, while Canadian keyboards are in QWERTY, so I would have to relearn to type. By extension, that also makes Latin-postfix unusable since the required keys are still dead :( I'll subscribe to issue 36 to get notified when you make progress on this feature. Until ibus fixes the menu positioning, I can't make much use of this anyway since I need to work in full-size windows with interfaces that are already a little starved for vertical space =/

In the meantime I'll try to remove Gnome and see if it fixes the XKB thing.

Thanks again for your time!

**Comment by mike-fabian** [comment]
OK, I’ll try to work on this soon. But first I’ll work on this:

https://github.com/mike-fabian/ibus-typing-booster/issues/48#issuecomment-463835770

this is considerably easier, dead key support is quite a big thing, I think it will be a lot of work but I really need to do that. 

By the way, now that I read again that you use Gnome: In case of Gnome3, the positioning of the candidate window is done by gnome-shell, not ibus. Only on the non-Gnome3 desktops, ibus draws the candidate window, on Gnome3 ibus support is integrated and gnome-shell draws this. So if the candidate window is positioned wrongly on Gnome3, I think it is a gnome-shell problem.

**Comment by Salvatos** [comment]
Good to know; maybe I'll try different OS and desktop combinations in a VM when the time comes to avoid breaking my main system again (glad I have Timeshift on!), and see what works best. I do like Cinnamon, but this could substantially reduce my problems with RSI so it's worth considering a switch for. Feel free to ping me if I can be of use!

**Comment by mike-fabian** [comment]
> > As a workaround for the meantime, you could try whether using some French keyboard layout which does not use dead keys works reasonably for you.
> 
> Unfortunately, all of those layouts are in AZERTY or QWERTZ, while Canadian keyboards are in QWERTY, so I would have to relearn to type. By extension, that also makes Latin-postfix unusable since the required keys are still dead :( I'll subscribe to issue 36 to get notified when you make progress on this feature. Until ibus fixes the menu positioning, I can't make much use of this anyway since I need to work in full-size windows with interfaces that are already a little starved for vertical space =/
> 
> In the meantime I'll try to remove Gnome and see if it fixes the XKB thing.
> 
> Thanks again for your time!

The [2.7.0 release](https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.7.0) has  support for Compose now, i.e. dead keys should now work with ibus-typing-booster 2.7.0 and you should be able to use your Canadian French keyboard layout with ibus-typing-booster.

**Comment by Salvatos** [comment]
Awesome! How long does it typically take for updates to hit fedora? I tried to install it manually in my test VM but it doesn't show up in the input methods.

**Comment by mike-fabian** [comment]
I’ll make an update for  Fedora 30 and Fedora  31 tomorrow. In the meantime you can try this build:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/

I  wonder what  went  wrong with your  attempt  to install it manually in your VM.
How did  you do that? And, in case you are using Gnome  you need to end you Gnome session and log in again to get ibus restarted and see new input methods.  On  other, non-Gnome desktops calling "ibus restart" from the command line is enough.

**Comment by Salvatos** [comment]
I was trying to install the files at https://apps.fedoraproject.org/packages/ibus-typing-booster but now I can see I didn't have the package for the right Fedora version. I thought the upgrade I'd just run had put me at F32 but I'm on F30. It did manage to install according to dnf, but I imagine something was missing.

Installing via the repo did work and I can confirm that accented characters are now behaving as expected on a French Canadian keyboard (except that normally they don't show up on their own when pressed once, but that's really not a problem since they get replaced according to the following key press). Many thanks, I'll try to look more into this in the near future :)

**Comment by mike-fabian** [comment]
> I was trying to install the files at https://apps.fedoraproject.org/packages/ibus-typing-booster but now I can see I didn't have the package for the right Fedora version. I thought the upgrade I'd just run had put me at F32 but I'm on F30. It did manage to install according to dnf, but I imagine something was missing.

Yes,  the F30  and F31 packages are not yet there at https://apps.fedoraproject.org/packages/ibus-typing-booster
Coming soon ...

> Installing via the repo did work and I can confirm that accented characters are now behaving as expected on a French Canadian keyboard (except that normally they don't show up on their own when pressed once, but that's really not a problem since they get replaced according to the following key press). Many thanks, I'll try to look more into this in the near future :)

That keys of a compose sequence are shown until the sequence is
finished was actually a bit more work to implement.  Mhy first
implementation didn’t show them, i.e. it looked the same as when using
a plain keyboard layout.

But when you have at least one ibus input method configured in Gnome,
ibus will also handle the keyboard layouts. When you switch away from
ibus-typing-booster to a plain keyboard layout, for example your
French Canadian layout, you will notice that ibus also shows the dead
keys until the sequence is finished. I wanted the same behaviour when
ibus-typing-booster is used. It would be a bit weird if when a keyboard
layout is selected in the Gnome panel the unfinished sequences are shown
and when ibus-typing-booster is selected they are not shown.
I thought it is more consistent if it looks the same in both cases.

So I did spend some extra effort to display the keys of a partially
typed compose sequence the same way ibus does it.

Personally I also find it helpful to see partial sequences, especially
when the sequences are a bit longer. There are some rather long
compose sequences, for example:

<Multi_key> <asciitilde> <dead_circumflex> <A> 	: "Ẫ"   U1EAA # LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE

And when I try to type a long sequence like that I find it helpful that I see

```
⎄~^
```

after typing <Multi_key> <asciitilde> <dead_circumflex>. When typing the final “A” this turns into “Ẫ”.

**Comment by Salvatos** [comment]
Interesting, I wasn't aware of that. Long sequences aren't a problem for me since I only ever need <diacritic> + <letter>, but I can see how it can be helpful in other languages :)

**Comment by mike-fabian** [comment]
On your French canadian keyboard you can probably type this one:


```
<dead_acute> <dead_cedilla> <c>  	: "ḉ"   U1E09 # LATIN SMALL LETTER C WITH CEDILLA AND ACUTE
```

But you don’t need that for writing French ☺

You could also add a ~/.XCompose file and define your own sequences. Here is mine
which I created just for testing whether the compose support in ibus-typing-booster
correctly uses ~/.XCompose as well, I don’t really use that myself:

```
<Multi_key> <U006D> <i> <k> <e> : "真意久"
<Multi_key> <plus> <plus> : "🙈🙉🙊"
<Multi_key> <y> <s> : "Yours sincerely,"

```

You could use gnome-tweaks to choose a key as the compose key (compose key = Multi_key)
and then add sequences as above to ~/.XCompose to define some shortcuts.

ibus-typing-booster has its own way of defining custom shortcuts in the setup tool already.
Therefore, I don’t really use compose for defining shortcuts, I only wanted to test this.
