### ISSUE TITLE
[BUG] First typed letter on WhatsApp web gets omitted on Firefox

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#471]
**Describe the bug**

In WhatsApp web using Firefox, many times, when starting typing a new word, the first letter does not get typed.

https://github.com/mike-fabian/ibus-typing-booster/assets/75945439/f28687d0-a310-4b43-83d6-76dfeb3eb3d9

**Screenshots or videos**

See attached video.

When `update` something appears, I had typed `que`, therefore omitting the letter `q`.

**ibus-typing-booster version?**

`ibus-typing-booster-2.24.4-1.fc39.noarch
`

**ibus version?**

`ibus-1.5.29~rc2-3.fc39.x86_64
`

**Distribution and version?**

`Fedora 39
`

**Desktop and version?**

`XFCE`

**Xorg or Wayland?**

`x11`

**Comment by psads-git** [comment]
The reported issue does not occur when using Chrome instead of Firefox. Notwithstanding, when the first character of the first word type in a new WhatsApp message, the word can never be typed. Please, see the attached video.

https://github.com/mike-fabian/ibus-typing-booster/assets/75945439/4931afd3-b75b-4c55-a383-061e835ecbfb

**Comment by mike-fabian** [comment]
By the way, you see to use inline completion in ibus-typing-booster and although you write that you use `XFCE` (i.e. `x11`) in your initial report, the inline completion shown is completely underlined and black. Usually, the inline completion should not be underlined and gray (gray is the default setting). One could change the default to black of course but there is no setting to make the inline completion underlined. 

If Wayland were used, it would look like that, the inline completion wouuld be black (because on Wayland currently colour in the preedit does not work) and the whole preedit would always be underlined (because currently there is no way to turn off underlining of the preedit in Wayland).

But you write that you used `XFDE` and `x11`, so this is weird, I wonder why your inline completion in your first video looks like that. Has that been recorded on Wayland maybe?

In your second video, the inline completion is not underlined and colour works, that is how it should be on `x11`.

**Comment by psads-git** [comment]
I have never used Wayland, Mike! I have used XFCE for years and years!

**Comment by psads-git** [comment]
Today, the vanishing of the first letter only occurs in the first word of the message, as long as its first letter is accented.

**Comment by psads-git** [comment]
I cannot explain that, Mike, but I assure you that I have _never_ used Wayland.

The `É` problem has occurred since very, very long ago, but I had never reported it.

**Comment by mike-fabian** [comment]
But it is great that I can reproduce this in ibus-typing-booster now, now I have something I can investigate. Thank you!

**Comment by mike-fabian** [comment]
Can you try ibus-typing-booster 2.24.5 from: https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/

This seems to fix it for me.

**Comment by psads-git** [comment]
Thanks, Mike! Apparently, it is now working fine.

**Comment by mike-fabian** [comment]
Thank you very much for testing! 

By the way, as you are a very active user of ibus-typing-booster, do you have an opinion about this:

https://github.com/mike-fabian/ibus-typing-booster/issues/470#issuecomment-1838419492

Would the change of the 

☑️ Off the record mode

option into a combobox options with 4 values bother you? 

Record mode [All | Dictionaries and user database | Dictionaries | Nothing]

Personally I never used the “☑️ Off the record mode” optioņ so that change would not bother me.

**Comment by psads-git** [comment]
In my personal use of `ibus-typing-booster`, I do not need the mentioned option, Mike. However, I believe that some people may find useful such an option. In this context, the proposed combobox alternative is better than the other one.

**Comment by mike-fabian** [comment]
Fix is included in ibus-typing-booster-2.24.5: https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.24.5

**Comment by psads-git** [comment]
While the initial `É` problem is fixed, Mike, from time to time, again on Firefox Web WhatsApp, in the middle of the message, when a new word is being started, the first character disappears. 

That occurs with not accented first characters, and I have not, until now, devised a systematic way of reproducing the issue. 

The issue does not occur when using Chrome.

**Comment by mike-fabian** [comment]
Does that occur only with certain letters, or is it completely independent of which letters you type? Does it depend on upper or lower case letters? Is AltGr involved?

**Comment by psads-git** [comment]
> Does that occur only with certain letters

I have not found a specific pattern. 

> , or is it completely independent of which letters you type? 

It appears so.

> Does it depend on upper or lower case letters?

It has occurred with lower case letters.

> Is AltGr involved?

No.

**Comment by psads-git** [comment]
> Does it depend on typing speed?

No, it does not. Henceforward, I will be paying closer attention, to device a reproduction path.

**Comment by mike-fabian** [comment]
I think I an reproduce that. It seems pretty rare but it seems to occur in this video: 


https://github.com/mike-fabian/ibus-typing-booster/assets/2330175/de1411bf-1087-4d56-9256-9ed867b0b248

Here I type `a` + `space` many times, slowly. When I typed this for the 14th time, the `a` vanished and only the space remained.

**Comment by mike-fabian** [comment]
I am using the option 

Minimum number of chars for completion    [   0]

Therefore you see the next `a` predicted in my video in orange. Are you also using the same value for this option?

**Comment by psads-git** [comment]
That is it, Mike! 

Yes, I am also using 0 for that option.

In the day I reported the issue, the problem was occurring extremely often.
