### ISSUE TITLE
feature-request: Gmail-style suggestions - right-arrow to select candidate 

### ISSUE THREAD

**Issue by pescepalla** [mike-fabian/ibus-typing-booster#48]
Thank you for implementing ibus-typing-booster. I'm just here to drop a suggestion: why not implementing right-arrow-key to autocomplete the inline candidate (the one shown in grey after the preedit) instead of pressing the "1" key?

This would be more intuitive and match Gmail's smart-compose behaviour.

**Comment by mike-fabian** [comment]
There is already an option like this. It is called “Use inline completion”.

It looks like this:

![ibus-typing-booster-inline-completion](https://user-images.githubusercontent.com/2330175/52791923-5effcd80-306a-11e9-8f02-8699a81bf664.png)

**Comment by pescepalla** [comment]
Yes, I am aware of this, and I'm using it.

Once ibus suggests the word, I can use  the "1" key to accept the suggestion and move the cursor to the end of the word, whereas it would be probably more intuitive if it was possible to use the right arrow instead.

At the moment, pressing the right arrow key makes the suggestion disappear and leaves me only with the preedit.

**Comment by mike-fabian** [comment]
Currently this option does the following:

If there is at least one suggestion candidate, *and* if the first suggestion candidate is  an extension  of what has been typed the first candidate is shown inline.

An extension of what has been typed means it is *not* a spellchecking suggestion changing something already typed and it is *not* a suggestion from a different script (i.e. maybe you typed Latin letters but got a first candidate in Hindi because you have Hindi transliteration turned on). Showing the candidate inline in this case is quite confusing, so I do it only if it is really an extension, i.e. does not change what has been typed already, it only makes it longer.

You can select this inline candidate by using the key bound to the command “select_next” candidate. The default key binding for this command is Tab and Down (arrow down). You can change these keybindings in the setup tool, if you like.

**Comment by mike-fabian** [comment]
That is very similar to what the Gmail completion does: If you continue typing in Gmail, the suggestion is discarded, if you type Tab or arrow right, the suggestion is accepted. The difference is only that Gmail uses Tab and arrow right by default for this and ibus-typing-booster uses Tab and arrow down (But you can change the key bindings).

If you type a key which commits after selecting with Tab, for example space, the selected first candidate is committed. If you type Tab again, this selects the second candidate and you see the usual popup appear with the second candidate selected. Escape (the key which is bound to the “cancel” command unselects all candidates).

As far as I know, the Gmail completion does not have more than one candidate, i.e. one cannot go to the "next" candidate in the Gmail completion.

Currently, this “Use inline completion” option is a checkbox, i.e. you can only switch it off or on.

I am thinking whether I should make that a combobox with 3 options:

1) No              (i.e. do not use inline completion, always use the popup)

2) First candidate (use inline completion for the first candidate as explained above)

3) Always          (Never show a popup, the second Tab or arrow down would put the second candidate into the inline display, candidates are always shown inline no matter whether it is a spellchecking candidate or a different script, whatever, always show it inline. I am not sure at the moment whether this would be a useful addition or just confusing.)

In Gmail, this inline suggestion is displayed in gray. That is also the default in ibus-typing-booster. You can change the colour in the setup tool. You can also uncheck the option “Use color for inline completion”, in that case the inline suggestion uses the same colour as the typed text, only it will not be underlined, if you select it with Tab it will be underlined.

There is a big problem in Wayland though: In Wayland, the preedit cannot be styled,
neither the colour nor the underlining for the preedit can be changed. In Wayland, the preedit is *always* in the same colour as regular text and *always* underline. Wayland just ignores the requests by ibus for preedit styles. That means, an inline completion looks *exactly* like the already typed text. If you look carefully, you can still see the difference between the typed text and the inline completion if you look where the cursor is. But that is hard to see. Because of this, I find inline completion very hard to use on Wayland.

See this for the problem with the Wayland preedit styling: https://gitlab.gnome.org/GNOME/mutter/issues/153

**Comment by mike-fabian** [comment]
> Yes, I am aware of this, and I'm using it.
> 
> Once ibus suggests the word, I can use the "1" key to accept the suggestion and move the cursor to the end of the word, whereas it would be probably more intuitive if it was possible to use the right arrow instead.
> 
> At the moment, pressing the right arrow key makes the suggestion disappear and leaves me only with the preedit.

You can use Tab or arrow down instead of "1" to accept the suggestion.

This does *not* move the cursor to the end though.

So if you want to insert that text into your application, you can type Tab followed by Space.

**Comment by mike-fabian** [comment]
You can bind  arrow-right in the setup tool to the command "select_next_candidate", then you can use arrow-right to select. That prevents you from using arrow-right to move around in the preedit though, therefore, I think Tab and arrow-down are better choices.

**Comment by pescepalla** [comment]
Thanks for the extensive answer. 

When ibus-typing-booster guesses the right word, the user wants to select it and to place the cursor 
where he can begin writing the next word with as little effort as possible.

So in your example, if I write:

> I am r

and ibus-typing-booster suggests "eading", I want a single handy keystroke to both 1) accept the suggestion and 2) place the cursor after "I am reading". 

Pressing Tab key satisfies 1) but I still need two keystrokes to get where I want to be. Using "1" satisfies both conditions, but it's not very handy.

So I'm wondering whether there was a way to bind a key to perform these two actions.

Apologies if this request sounds rather fastidious, it's really a small issue which does nothing to hide the usefulness of this ibus extension.

**Comment by mike-fabian** [comment]
If  you type "I am r" + Tab + Space, you have "I am reading ". No extra key stroke because you need  the space anyway. 

It is bit different if you want "I am reading." Because by default, the "." would not commit but continue the input. I.e. typing "I am r" + Tab + "." would  give you "I am r.". Currently, if a candidate is selected and you type a key which does generate  further input, the new input cancels the selection and is added to the existing input.

So only in case of typing stuff like .,;:? you need extra keystrokes because either you commit as usual with Space, remove the Space with Backspace and add the ".". That is 2 extra keys. Or, you commit with Control+Space which commits but does not add the space after the commit and then type ".". Then it is only one extra key, the Control key, each time you want to add one of .,;:?

But such punctuation characters occur less often after a commit than a space, so in
most cases, when a space after the commit is OK, you need no extra keys at all,
just type "I am r" + Tab + Space.

I am not sure, I am thinking whether it might be useful to change the behaviour to avoid extra keys even in case of adding punctuation.

Currently if you type any input character (letters, punctuation, anything which is input and does not commit) while a candidate list is shown, it does not matter whether a candidate is selected or not, in  both cases the candidate list is closed, the new letter is added to the preëdit and a new candidate list is calculated.

I feel it might be better to treat both cases separately.

1) if no candidate is selected, add the new input character to the preëdit (same as current behaviour)

2) If a candidate is selected, put that candidate into the preëdit and add the new input character to the end of the updated preedit.

With that new behaviour implemented this would happen:

   "I am r" + ". " would give  "I am r. "

(Because no candidate was selected)

   "I am r" + Tab + ". " would give "I am reading. "

(Because the Tab selected the "reading" candidate and then the "." would added to the selected candidate so you would have "reading." in the preëdit and then the final space would commit giving you the "reading. ".

This new idea would avoid any extra keys when adding anything wether it is letters or punctuation to selected candidates.

You could still say that typing the final space is one key too much if you really wanted "I am reading." and not "I am reading. " because to avoid that final space you would need to remove it with Backspace or use Control+Space to do the commit. But I think it is *very* rare not to want a space after punctuation, usually the next sentence follows and you want the space anyway.

What do you think about this idea for improved behaviour?

**Comment by pescepalla** [comment]
As to Tab+Space, it's a very good point, but given the fact that it's so common, maybe there should be an option performing the same with a single keystroke. At the moment, as a workaround, I'll keep using "1" as it saves me one keystroke.
As to the Tab+[punctuation], I think it's a great idea as it's how I would expect the application to behave. In fact, I thought that this was exactly what the "Autocommit characters" option did when I first saw in the preferences.

**Comment by mike-fabian** [comment]
OK, so probably I should implement the  above idea to add punctuation (and letters) to selected candidates.

You are right that "1" saves one keystroke if you have the option "Add a space when committing by label or mouse" at its default value, which is on, because in that case the "1" selects  the 1st candidate, commits it and adds a space.

I have the following  additional idea:

Make the thing which "1" does a configurable keybinding  as well. I.e. add a command

“commit_candidate_1"

which  would be  bound by  default to "1" and  "F1" (as  it  is now).

Then you could add arrow right or whatever you like  to that  keybinding. 

That sounds useful in addition to the idea in my previous comment, maybe I should do both.

If I implemented a command “commit_candidate_1", then it is probably no extra work to implement also "commit_candidate_2" (default  keys "2"  and "F2") ... "commit_candidate_9" (default  keys  "9" and  "F9"). 

I am  not sure how useful that  would be to have it for all candidates 1-9 and not  only for one, but the effort to implement it is the same I think.

**Comment by pescepalla** [comment]
Making it possible to configure "commit_candidate_1" sounds exactly what I was looking for!

One more useful feaure would perhaps be a single keybinding leaving the cursor right at the end of the first candidate word. This would be useful in case I wanted to add a slight modification to the candidate.
For example, if I pre-edit: 
> I w
and ibus-typing-booster suggests "ant" whereas I intended to complete with "anted", I could still do it with a single keystroke plus the missing letters instead of having to either delete one space or ignore the suggestion. I'd personally bind that to the left-arrow.

**Comment by mike-fabian** [comment]
OK, then I have an additional idea how to do that:

Currently, there is an option "Add a space when committing by label or mouse" which is on by default.

If it is on, committing with 1-9 or F1-F9 or clicking with the mouse on a candidate adds a space.

Somebody wanted this without space and I added this option although I had some doubts about its usefulness. Now I think I should change this option to "Add a space when commiting by mouse" and make it have an effect only on commits by mouse clicks and no effect on commits by
keybindings.

And for the commits using keys I think it would be good to have commands like:

commit_candidate_1              []         <- default keybinding empty
commit_candidate_1_with_space   [1, F1]    <- default keybinding not empty
... same for  2-9 ...

Somebody who wants to use 1-9 to commit without space would need to remove the 1-9 keybindings from “commit_candidate_1_with_space” and add them to “commit_candidate_1”. That is a bit  more work than just clicking the current checkbox, but I don’t think it makes sense to change this setting often.

If I implement it that way, I would remove the option “Use digits as select keys” completely. Because this option does not make sense anymore then. If one does not want to use digits as select keys, one could remove 1-9 from the above key bindings. A few more clicks than just checking or unchecking the checkbox of “Use digits as select keys” but I think this is no problem either. I don’t think anybody changes this option often. Either one wants to use the digits as select keys or one wants to be able to type digits into the preedit. Changing this option often seems not useful.

Having commands “commit_candidate_?” and “commit_candidate_?_with_space” with freely configurable keybindings gives much more flexibility to fine tune the behaviour to ones personal taste than the current solution.

I think I’ll start implementing this next week.

**Comment by mike-fabian** [comment]
I also asked the reporter of this old issue whether implementing the above idea would make anything worse for him:

https://github.com/mike-fabian/ibus-typing-booster/issues/39

Apparently not, he does not  change the "Add a space when committing by label or mouse" often, so I there seems to no reason against implementing the above idea.

**Comment by mike-fabian** [comment]
Are you using Fedora? If yes, could you test a  build if I make a copr build with the new feature?

**Comment by pescepalla** [comment]
I'm on Arch Linux. Let me know if I can still help.

**Comment by mike-fabian** [comment]
Do you use some official package or do you build and install  from source?
Could you install from source if I push a branch to github for you to test?
Or should  I  better upload a tarball for you to test?

**Comment by pescepalla** [comment]
I use the official package here: https://www.archlinux.org/packages/extra/any/ibus-typing-booster/

I could also clone the GitHub branch and build, no problem.

**Comment by mike-fabian** [comment]
I have pushed a test branch for the 2.6.0 release: 

https://github.com/mike-fabian/ibus-typing-booster/tree/release-2.6.0-rc1

Most  important  changes  for you in this  branch are: 

- Make key bindings to commit or remove candidates via label configurable
- If an input char is typed while a candidate is selected, add that input to the candidate

The second one is the  “Tab+[punctuation]” thing we  discussed above.

**Comment by mike-fabian** [comment]
After testing rc1 for a while I found a small problem and added another patch. Here is rc2:

https://github.com/mike-fabian/ibus-typing-booster/tree/release-2.6.0-rc2

The new patch included does this:

-  When Left or BackSpace trigger a commit, forward Left events only when no candidate was selected (i.e. the preëdit was committed)

**Comment by pescepalla** [comment]
I can't seem to find an option to configure committing or removing candidates. Am I looking in the wrong place? Right now, there's no way to select other candidates than the first.

![screenshot_2019-02-21_11-39-50](https://user-images.githubusercontent.com/46329185/53163085-a091fa80-35cd-11e9-907c-e46bba0ec335.png)

Tab+punctuation correctly adds a space after the punctuation. I think a way to improve this would be an option to automatically remove the space if the "Return" key is hit after it, as in starting a new paragraph.

**Comment by pescepalla** [comment]
I'm testing rc2 now. 
Arrow-keys don't commit for me. Right-arrow moves right and left-arrow clears the preedit. 
Did I miss some setting?

**Comment by mike-fabian** [comment]
> I can't seem to find an option to configure committing or removing candidates. Am I looking in the wrong place?
> 
> ![screenshot_2019-02-21_11-39-50](https://user-images.githubusercontent.com/46329185/53163085-a091fa80-35cd-11e9-907c-e46bba0ec335.png)
> 
> Tab+punctuation correctly adds a space after the punctuation. I think a way to improve this would be an option to automatically remove the space if the "Return" key is hit after it, as in starting a new paragraph.

No, the screenshot looks wrong. It does not show the new commands.
It should look like this:

![ibus-typing-booster-new-commands-in-key-bindings](https://user-images.githubusercontent.com/2330175/53165123-32036b80-35d2-11e9-8024-aab6fee0f349.png)

**Comment by pescepalla** [comment]
Nothing like that in my settings, although I'm using 2.6.0.

![screenshot_2019-02-21_12-15-17](https://user-images.githubusercontent.com/46329185/53165226-73941680-35d2-11e9-98ce-12ed59d7f30c.png)

**Comment by mike-fabian** [comment]
I think you need to manually compile the  schema.  The "sudo make install"  does  install the  file org.freedesktop.ibus.engine.typing-booster.gschema.xml to 

/usr/share/glib-2.0/schemas/org.freedesktop.ibus.engine.typing-booster.gschema.xml

but fails to recompile the schemas.

You need to manually do:

sudo glib-compile-schemas  /usr/share/glib-2.0/schemas/

Then the new options should appear.

**Comment by pescepalla** [comment]
I'm not sure why it doesn't work. I've recompiled the schema and I still cannot see the new options even after a fresh `make install`.

**Comment by mike-fabian** [comment]
Is there any  interesting  stuff in the log files?:

~/.local/share/ibus-typing-booster/debug.log
 ~/.local/share/ibus-typing-booster/setup-debug.log

**Comment by mike-fabian** [comment]
Were there any error messages when recompiling the schemas?

**Comment by pescepalla** [comment]
No output on recompiling the schemas.
The logs appear all right.
[debug.log](https://github.com/mike-fabian/ibus-typing-booster/files/2889072/debug.log)
[setup-debug.log](https://github.com/mike-fabian/ibus-typing-booster/files/2889074/setup-debug.log)

**Comment by mike-fabian** [comment]
On Fedora the ibus-typing-booster start scripts are in:

/usr/libexec/ibus-engine-typing-booster
/usr/libexec/ibus-setup-typing-booster

On Arch Linux they seems to be in (according  to the file list at  https://www.archlinux.org/packages/extra/any/ibus-typing-booster/):

usr/lib/ibus/ibus-engine-typing-booster
usr/lib/ibus/ibus-setup-typing-booster

So I think when building from git you need the --libexecdir option for configure:

./autogen.sh  --prefix=/usr --libexecdir=/usr/lib/ibus
./configure --prefix=/usr --libexecdir=/usr/lib/ibus

But this should not  have any effect on the schema ...

**Comment by mike-fabian** [comment]
Do the  contents  of the installed  schema file look  OK? Are the new  options there? It should look like:
```
$ grep -A 10 'name="keybindings"'  /usr/share/glib-2.0/schemas/org.freedesktop.ibus.engine.typing-booster.gschema.xml 
    <key name="keybindings" type="a{sv}">
      <default>
        {
        'cancel': &lt;['Escape']&gt;,
        'commit_candidate_1': &lt;@as []&gt;,
        'commit_candidate_1_plus_space': &lt;['1', 'KP_1', 'F1']&gt;,
        'commit_candidate_2': &lt;@as []&gt;,
        'commit_candidate_2_plus_space': &lt;['2', 'KP_2', 'F2']&gt;,
        'commit_candidate_3': &lt;@as []&gt;,
        'commit_candidate_3_plus_space': &lt;['3', 'KP_3', 'F3']&gt;,
        'commit_candidate_4': &lt;@as []&gt;,
       ...
```

**Comment by mike-fabian** [comment]
> No output on recompiling the schemas.
> The logs appear all right.
> [debug.log](https://github.com/mike-fabian/ibus-typing-booster/files/2889072/debug.log)
> [setup-debug.log](https://github.com/mike-fabian/ibus-typing-booster/files/2889074/setup-debug.log)

Yes, the logs look OK.

**Comment by mike-fabian** [comment]
You did use "sudo" for "make install" and for compiling the schemas, right? So there was no permission error when installing or compiling the schemas?

**Comment by pescepalla** [comment]
So I've started from scratch.

`$ ./autogen.sh --prefix=/usr --libexecdir=/usr/lib/ibus`
`$ ./configure --prefix=/usr --libexecdir=/usr/lib/ibus`
`$ make`
`$ sudo make install`
`$ sudo glib-compile-schemas /usr/share/glib-2.0/schemas/`
`$ grep -A 10 'name="keybindings"'  /usr/share/glib-2.0/schemas/org.freedesktop.ibus.engine.typing-booster.gschema.xml`
Here's the output: [grep-output.log](https://github.com/mike-fabian/ibus-typing-booster/files/2889211/grep-output.txt)

**Comment by pescepalla** [comment]
The only error I get is by running a `make check`. I don't know if it's related but here it is:
[make-check.log](https://github.com/mike-fabian/ibus-typing-booster/files/2889246/make-check.log)

**Comment by mike-fabian** [comment]
The grep  output is OK, it contains  the new options.

You should already be able to see the new options in the setup tool if  you start the setup tool from your build directory like this;
```
$ python3 setup/main.py
```

**Comment by mike-fabian** [comment]
> The only error I get is by running a `make check`. I don't know if it's related but here it is:
> [make-check.log](https://github.com/mike-fabian/ibus-typing-booster/files/2889261/make-check.log)


What is in:

tests/test-suite.log

?

**Comment by pescepalla** [comment]
No, it still won't show the new options:
![screenshot_2019-02-21_13-58-40](https://user-images.githubusercontent.com/46329185/53170605-d2608c80-35e0-11e9-8cff-c4506e81b2b5.png)

[test-suite.log](https://github.com/mike-fabian/ibus-typing-booster/files/2889347/test-suite.log)

**Comment by mike-fabian** [comment]
Does

```
gsettings get org.freedesktop.ibus.engine.typing-booster keybindings
```

output anything interesting?

**Comment by pescepalla** [comment]
[keybindings.log](https://github.com/mike-fabian/ibus-typing-booster/files/2889652/keybindings.log)

**Comment by mike-fabian** [comment]
Oh, sorry, asking for the gsettings output was useless, it shows of course the user settings if there are any (and you have user settings of course). It would only show the system settings for keybindings if the user setting for keybindings were empty. So this doesn't help.
Thinking ...

**Comment by mike-fabian** [comment]
Can you do "git pull" again for the release-2.6.0-rc2 branch?

I added one commit to output to that branch to add some more debug messages in the setup tool.

After git pull, try

python3 setup/main.py 

again and see what is now in the debug log:

tail -F ~/.local/share/ibus-typing-booster/setup-debug.log

**Comment by pescepalla** [comment]
[setup-debug-tail.log](https://github.com/mike-fabian/ibus-typing-booster/files/2889753/setup-debug-tail.log)

**Comment by mike-fabian** [comment]
Weird, this setup-debug.log contains:

```
System settings: self._gsettings.get_default_value('keybindings')={'enable_lookup': ['Tab', 'ISO_Left_Tab'], 'select_next_candidate': ['Tab', 'ISO_Left_Tab', 'Down', 'KP_Down'], 'select_previous_candidate': ['Shift+Tab', 'Shift+ISO_Left_Tab', 'Up', 'KP_Up'], 'lookup_table_page_up': ['Page_Up', 'KP_Page_Up', 'KP_Prior'], 'lookup_table_page_down': ['Page_Down', 'KP_Page_Down', 'KP_Next'], 'cancel': ['Escape'], 'next_input_method': ['Control+Down', 'Control+KP_Down'], 'previous_input_method': ['Control+Up', 'Control+KP_Up'], 'next_dictionary': ['Mod1+Down', 'Mod1+KP_Down'], 'previous_dictionary': ['Mod1+Up', 'Mod1+KP_Up'], 'toggle_emoji_prediction': ['Mod5+F6'], 'toggle_off_the_record': ['Mod5+F9'], 'lookup_related': ['Mod5+F12'], 'toggle_hide_input': ['Shift+Control+Escape'], 'toggle_input_mode_on_off': [], 'speech_recognition': [], 'setup': ['Mod5+F10']}
```

So self._gsettings.get_default_value('keybindings') does somehow *not* get the new default value of 'keybindings'. 

It should get that value from  /usr/share/glib-2.0/schemas/org.freedesktop.ibus.engine.typing-booster.gschema.xml . 

Because we already saw the result  of this in your screenshots, I guessed that something 
went wrong with installing that file.

But we already checked that this file has the  new default  value for keybindings by looking into that file.

So I guessed that something went wrong with the 

sudo glib-compile-schemas  /usr/share/glib-2.0/schemas/

because gsettings doesn't read that file directly, it  reads the compiled version.

Really weird.

**Comment by mike-fabian** [comment]
Here I see that the new settings are in the database of compiled gschemas  on  my system:

```
$ strings /usr/share/glib-2.0/schemas/gschemas.compiled | grep commit_candidate_1
commit_candidate_1
commit_candidate_1_plus_space
```

Do you see that as well?

**Comment by pescepalla** [comment]
Yes, the output is the same.

**Comment by mike-fabian** [comment]
That means the 

```
sudo glib-compile-schemas  /usr/share/glib-2.0/schemas/
```

worked, I think.

**Comment by mike-fabian** [comment]
Does
```
sudo find / -name gschemas.compiled
```
find  any more such files except
```
/usr/share/glib-2.0/schemas/gschemas.compiled
```

?

**Comment by pescepalla** [comment]
/usr/share/glib-2.0/schemas/gschemas.compiled
/usr/local/share/glib-2.0/schemas/gschemas.compiled

**Comment by mike-fabian** [comment]
Ah, maybe gsettings prefers reading from /usr/local/share/glib-2.0/schemas/ ?
Is there a /usr/local/share/glib-2.0/schemas/org.freedesktop.ibus.engine.typing-booster.gschema.xml

If  yes, does it have the old contents (lacking the new keybindings options)?

If yes, remove that file and compile that folder again:

```
sudo /usr/local/share/glib-2.0/schemas/org.freedesktop.ibus.engine.typing-booster.gschema.xml
sudo sudo glib-compile-schemas  /usr/local/share/glib-2.0/schemas/
```

**Comment by pescepalla** [comment]
Yes! It works now. Thank you.

**Comment by mike-fabian** [comment]
Good, I am relieved.  Let me know how it works for you and whether you can configure the behaviour you want.

**Comment by pescepalla** [comment]
Yes, I did a bit of testing on the release candidate and it works beautifully.

I'm going to wait for the release, then build it. I'll let you know then.
