### ISSUE TITLE
[BUG] Space before punctuation character is not eliminated

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#564]
Hi, Mike,

This is something minor. The attached video is self-explanatory.

The issue occurs in chatGPT, using chrome on XFCE.

Thanks in advance!

https://github.com/user-attachments/assets/c29e1e3f-48bb-4a25-8715-fe6f7bf619b8

**Comment by mike-fabian** [comment]
Which browser? Works for me in firefox. It cannot work in google-chrome because google chrome does not support surrounding 
text. You can confirm that by doing with debug level >= 1: 

```
$ tail -F ~/.local/share/ibus-typing-booster/debug.log | grep _update_candidates_and_lookup_table_and_aux
```

Then, when typing in firefox and candidates are updated, you see some information about the surrounding text detected. Like this:

```
2024-11-20 16:44:14,510 hunspell_table.py line 2619 _update_candidates_and_lookup_table_and_aux DEBUG: surrounding_text = ['\n', 1, 1]
```

But when doing that in google-chrome, you get nothing.


That is because of:

```python
    def _update_candidates_and_lookup_table_and_aux(self) -> None:
        '''Update the candidates, the lookup table and the auxiliary text

        :return: None, always, which is falsy and should work
                 the same as `return False` to remove the source
                 added by Glib.timeout_add() (GLib.SOURCE_REMOVE is False)
        '''
        if self._label_busy and self._label_busy_string.strip():
            # Show a label in the auxiliary text to indicate that the
            # lookup table is being updated (by default an hourglass
            # with moving sand):
            super().update_auxiliary_text(
                IBus.Text.new_from_string(
                    self._label_busy_string.strip()), True)
        else:
            super().update_auxiliary_text(
                IBus.Text.new_from_string(''), False)
        self._update_candidates()
        self._update_lookup_table_and_aux()
        if DEBUG_LEVEL < 1:
            return
        if not self.client_capabilities & itb_util.Capabilite.SURROUNDING_TEXT:
            return
        surrounding_text = self.get_surrounding_text()
        if not surrounding_text:
            LOGGER.debug('Surrounding text object is None. '
                         'Should never happen.')
            return
        LOGGER.debug('surrounding_text = [%r, %s, %s]',
                     surrounding_text[0].get_text(),
                     surrounding_text[1], surrounding_text[2])
```

If surrounding text ist not supported, then 

```python
        if not self.client_capabilities & itb_util.Capabilite.SURROUNDING_TEXT:
            return
```

just returns and nothing is printed.

If surrounding text is supported, then the code below which fetches the surrounding text and prints it into the log is executed.

You can also see that surrounding text is not supported in google-chrome when you type in google-chrome with debug level > 2 and you always see the red circle 🔴 (which means context is not from surrounding text) and never the green circle 🟢 (which means  context could be obtained from surrounding text). 

To adjust the punctuation, surrounding text support is required, ibus-typing-booster needs to check whether there is whitespace before the punctuation and then remove it. I.e. both `self.get_surrounding_text()` and `self.delete_surrounding_text(-nchars, nchars)` need to work.

**Comment by mike-fabian** [comment]
> The issue occurs in chatGPT, using chrome on XFCE.

Ah, I see now that you wrote that you use google-chrome, so I didn't need to ask.

Cannot work with chrome. That needs to be fixed in google-chrome, surrounding text needs to be supported, not in typing-booster.

**Comment by mike-fabian** [comment]
See also: https://github.com/ibus/ibus/issues/2354

**Comment by psads-git** [comment]
Thanks, Mike! I understand that the issue lies on Chrome and not on `ibus-typing-booster`. Fortunately, it is a very minor issue.

**Comment by psads-git** [comment]
Thanks, @mike-fabian!
