### ISSUE TITLE
"preëdit"

### ISSUE THREAD

**Issue by rffontenelle** [mike-fabian/ibus-typing-booster#62]
Is **preëdit** a valid English word? Normally "preedit" is used, but there some "preëdit" in the source code, e.g. README.md, typing-booster.appdata.xml, ibus-typing-booster.spec.fedora, and more. See [search result](https://github.com/mike-fabian/ibus-typing-booster/search?utf8=%E2%9C%93&q=pre%C3%ABdit&type=).

**Comment by mike-fabian** [comment]
https://en.wikipedia.org/wiki/Diaeresis_(diacritic)#Diaeresis

“In British English this usage has been considered obsolete for many years, and in US English, although it persisted for longer, it is now considered archaic as well.[4] Nevertheless, it is still used by the US magazine The New Yorker.[5] ”

https://www.newyorker.com/culture/culture-desk/the-curse-of-the-diaeresis

I found it funny that the New Yorker still does this and used it myself because I found this funny.
It should not be in English message ids which translators need to translated. I think in comments in the source code,  and in documentation like the README.md, it is harmless and a bit funny.

**Comment by mike-fabian** [comment]
https://www.theatlantic.com/entertainment/archive/2012/04/we-resist-further-cooperation-cooperation/328832/

**Comment by rffontenelle** [comment]
That was very instructive: I only knew these "two dots" as umlaut (it was used in Brazilian Portuguese until the [new orthographic agreement](https://en.wikipedia.org/wiki/Portuguese_Language_Orthographic_Agreement_of_1990)), but after reading the New Yorker I learned that umlaut ≠ diaeresis. Thank you, sir.

> It should not be in English message ids which translators need to translated.

Actually it came to my attention due while translating the following string from [setup/main.py, line 1100](/mike-fabian/ibus-typing-booster/blob/master/setup/main.py#L1100):

> "Show in the auxiliary text whether “Emoji prediction”  mode and “Off the record”  mode are on or off and show which input method is currently used for the **preëdit**. The auxiliary text is an optional line of text displayed above the candidate list."

For consistency, my suggestion is to change preëdit → preedit in the above string.

**Comment by mike-fabian** [comment]
Yes, you are  right,   there it is in a English message ID. That will just confuse translators, Í’ll fix it.
