### ISSUE TITLE
Key bindings do not work at all with Greek keyboard layout

### ISSUE THREAD

**Issue by simos** [mike-fabian/ibus-typing-booster#94]
I am using _ibus-typing-booster 2.8.2_ as packaged in this PPA for Ubuntu 20.04,
https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-typing-booster
Using the NoIME (Native Keyboard) input method.

It worked without any additional change over the _English US_ keyboard layout. For example, when typing, I could use the _arrow keys_ to select a candidate suggestion. Or use the _Fn_ keys for the selection. Or even use any of the _AltGr_ key bindings. 

However, when I tried with the Greek keyboard layout, none of these worked.
Pressing any of the arrow keys, Fn keys or AltGr key bindings would cancel the preedit window.

In the Greek keyboard layout the AltGr key does emit a `ISO_Level3_Shift` keysym:
```
KeyPress event, serial 37, synthetic NO, window 0x5600001,
    root 0x205, subw 0x5600002, time 5215736, (57,29), root:(212,176),
    state 0x10, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Do you have any suggestion as to where to look at?

**Comment by mike-fabian** [comment]
> In the Greek keyboard layout the AltGr key does emit a ISO_Level3_Shift keysym:

That is good!

**Comment by mike-fabian** [comment]
> Pressing any of the arrow keys, Fn keys or AltGr key bindings would cancel the preedit window.

Do you see a candidate window? If not, maybe you do not have a Greek dictionary installed?
Or, maybe you have it installed, but didn’t add it in the ibus-typing-booster setup tool?

If there are no candidates, something like arrow-down would commit the preedit. 
For example, if you type:

αλφάβητο

and there are no candidates, than arrow down/up would commit the word αλφάβητο, i.e. the underline indicating the preedit disappears. But in that case, if you type 

αλφ

again, you should now see αλφάβητο in the candidate list because it has been recorded into the user database and αλφάβητο is a match for αλφ. Then arrow-down should select it.

**Comment by mike-fabian** [comment]
With a Greek dictionary installed and selected in the setup tool of ibus-typing-booster, it should look like this:

![Screenshot](https://user-images.githubusercontent.com/2330175/81550238-3d31eb00-9380-11ea-80ab-ae0c2cf32563.png)

(Screenshot from Fedora 32, but it should be the same on Ubuntu).

I selected the candidate number 4 by typing arrow-down 4 times.

**Comment by simos** [comment]
Thanks for the reply. 

Here is [a video that demonstrates the issue](https://streamable.com/5z4709).

I get the same output as your last screenshot. 
The candidate window appears as it should, but when I press a number to select a candidate, the number is printed on the screen and not the candidate text. As if the candidate window does not have the keyboard input.

1. In Line 1 in the video, I type a bit in Greek, and attempt to press 3 to select the third candidate. Instead, the number 3 is typed.
2. In Line 3 in the video, I use the arrow keys to select any candidate. The candidate window disappears, as if it is cancelled. 

When I type in the English layout, the candidate window works as intended.

**Comment by mike-fabian** [comment]
You didn’t change the keybindings in the settings, right?

Can you pasted the output of
``
dconf dump /org/freedesktop/ibus/engine/typing-booster/
``
here, just in case, so I can check your key bindings settings?

Which Greek keyboard layout exactly are you using?
Can you paste the output of
``
setxkbmap -print
``
please? This should show which variation of the Greek keyboard layout you are using.

**Comment by simos** [comment]
I did not change the keybindings. Here is the output,
```
$ dconf dump /org/freedesktop/ibus/engine/typing-booster/
[/]
arrowkeysreopenpreedit=true
dictionary='en_US,el_GR'
emojipredictions=false
inlinecompletion=false
inputmethod='NoIME'
keybindings={'remove_candidate_6': <['Control+6', 'Control+KP_6', 'Control+F6']>, 'remove_candidate_2': <['Control+2', 'Control+KP_2', 'Control+F2']>, 'commit_candidate_5': <@as []>, 'next_input_method': <['Control+Down', 'Control+KP_Down']>, 'lookup_table_page_up': <['Page_Up', 'KP_Page_Up', 'KP_Prior']>, 'remove_candidate_8': <['Control+8', 'Control+KP_8', 'Control+F8']>, 'setup': <['Mod5+F10']>, 'select_previous_candidate': <['Shift+Tab', 'Shift+ISO_Left_Tab', 'Up', 'KP_Up']>, 'previous_input_method': <['Control+Up', 'Control+KP_Up']>, 'commit_candidate_6': <@as []>, 'remove_candidate_3': <['Control+3', 'Control+KP_3', 'Control+F3']>, 'lookup_related': <['Mod5+F12']>, 'select_next_candidate': <['Tab', 'ISO_Left_Tab', 'Down', 'KP_Down']>, 'remove_candidate_9': <['Control+9', 'Control+KP_9', 'Control+F9']>, 'commit_candidate_1': <@as []>, 'remove_candidate_4': <['Control+4', 'Control+KP_4', 'Control+F4']>, 'commit_candidate_7': <@as []>, 'next_dictionary': <['Mod1+Down', 'Mod1+KP_Down']>, 'toggle_input_mode_on_off': <@as []>, 'commit_candidate_2': <@as []>, 'speech_recognition': <@as []>, 'commit_candidate_8': <@as []>, 'lookup_table_page_down': <['Page_Down', 'KP_Page_Down', 'KP_Next']>, 'remove_candidate_5': <['Control+5', 'Control+KP_5', 'Control+F5']>, 'toggle_emoji_prediction': <['Mod5+F6']>, 'toggle_hide_input': <['Shift+Control+Escape']>, 'commit_candidate_3': <@as []>, 'toggle_off_the_record': <['Mod5+F9']>, 'cancel': <['Escape']>, 'enable_lookup': <['Tab', 'ISO_Left_Tab']>, 'commit_candidate_9': <@as []>, 'previous_dictionary': <['Mod1+Up', 'Mod1+KP_Up']>, 'commit_candidate_1_plus_space': <['1', 'KP_1', 'F1']>, 'commit_candidate_2_plus_space': <['2', 'KP_2', 'F2']>, 'commit_candidate_3_plus_space': <['3', 'KP_3', 'F3']>, 'commit_candidate_4_plus_space': <['4', 'KP_4', 'F4']>, 'commit_candidate_5_plus_space': <['5', 'KP_5', 'F5']>, 'commit_candidate_6_plus_space': <['6', 'KP_6', 'F6']>, 'commit_candidate_4': <@as []>, 'commit_candidate_7_plus_space': <['7', 'KP_7', 'F7']>, 'commit_candidate_9_plus_space': <['9', 'KP_9', 'F9']>, 'remove_candidate_1': <['Control+1', 'Control+KP_1', 'Control+F1']>, 'commit_candidate_8_plus_space': <['8', 'KP_8', 'F8']>, 'remove_candidate_7': <['Control+7', 'Control+KP_7', 'Control+F7']>}
tabenable=false
$ 
```

I am using the default Greek keyboard layout. 
```
$  setxkbmap -print
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete+ledscroll(group_lock)"	};
	xkb_symbols   { include "pc+us+gr:2+gr:3+inet(evdev)+level3(ralt_switch)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
$ 
```

**Comment by mike-fabian** [comment]
I installed Ubuntu (ubuntu-20.04-desktop-amd64.iso) and can reproduce you problem there.

**Comment by mike-fabian** [comment]
The problem occurs only when using Gnome Xorg, not when using Gnome Wayland.

I can reproduce it on Gnome Xorg on Fedora 32 as well now.

**Comment by mike-fabian** [comment]
The fix is included in this release:

https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.9.0

**Comment by gunnarhj** [comment]
I'm glad to see that this issue was fixed so fast, @mike-fabian.

Want to mention that I'm about to add `ibus-typing-booster` to Debian and with that Ubuntu. It's currently in [Debian's NEW queue](https://ftp-master.debian.org/new/ibus-typing-booster_2.8.2-1.html). Since Ubuntu still defaults to Xorg, the number of `ibus-typing-booster` users on Xorg will hopefully increase soon.

Thanks for your great work with this tool! Personally I wasn't aware of its existence before @simos called my attention to it a few weeks ago. I believe it has a great potential.

**Comment by mike-fabian** [comment]
Thank you for packaging it for Debian and Ubuntu! That is so great!

Actually, at the moment, I would recommend Xorg with ibus-typing-booster, there are still a few problems with Wayland which are very annoying:

- Surrounding text is even more broken on Wayland than on Xorg (although it is quite buggy on Xorg too, but on Wayland it is completely unusable).  I heard that some work on this has been done recently, maybe that will improve soon.
- Colours and underlining in the preedit don’t work in Wayland. In Wayland, the preedit is always completely underlined and the colour cannot be changed. That is bad when trying to use the option "Use inline completion" , this option is very hard to use on Wayland. And the option "Preedit spellchecking" does not work on Wayland at all.

Personally I mostly use ibus-typing-booster on Xorg with the i3 window manager. And I test often in a virtual machine running Gnome. I test both Wayland and Xorg there, I wonder how I missed this bug. 

Surprisingly, this bug happens only under Gnome Xorg, it doesn't happen under Gnome Wayland and it doesn’t happen when using Xorg with other window managers either. 

And on Gnome Xorg this bug occurs only if one has more than one keyboard layout configured. It works for every third keyboard layout then. For example, if one has the keyboard layouts "en, gr, de, jp, fr, it" setup in the gnome panel, then it will work only with "en" and "jp" but not with "gr", "de", "fr", and "it". Seems to be caused by Gnome grouping the keyboard layouts in groups of  3 internally and if one switches within a group of 3, only one bit is changed and the layouts are not parse again. Which is probably a performance optimization. But that causes some bits in the "state" (can be shown with xev) to be set and when these bits were set, my matching for keybindings failed because the state was not identical. Now I ignore all bits which are not really modifier bits when matching key bindings (I already ignored Caps Lock and Num Lock, key bindings like arrow-down should work no matter whether Caps Lock or Num Lock are on or off. But I didn’t ignore some other bits in state so far, I didn’t know that they could be set in some circumstances).

**Comment by mike-fabian** [comment]
There is nothing special with the Greek layout by the way, it is just the order. If one has the order "gr", "en", "de", in the Gnome panel, then "gr" worked but "en" and "de" did not work. After the fix this works for all keyboard layouts.
