### ISSUE TITLE
Allow to delete all dictionaries in setup tool

### ISSUE THREAD

**Issue by akiross** [mike-fabian/ibus-typing-booster#98]
As discussed in this comment https://github.com/mike-fabian/ibus-typing-booster/issues/93#issuecomment-626874368 it could be useful to exclude all dictionaries.

**Comment by mike-fabian** [comment]
While investigating how to do this, I found a bug and fixed it:

https://github.com/mike-fabian/ibus-typing-booster/commit/b938e13c299af43de0b0d71cdc15088029db01e6

Before that fix, if you deleted all dictionaries in the setup tool, the dictionaries which are the default for the current locale were automatically added back (in your case this was probably the en_US dictionary.

But that default setting was not saved to gsettings/dconf. I.e. when you then checked the dconf setting you would find:

``
$ dconf read  /org/freedesktop/ibus/engine/typing-booster/dictionary 
''
``
I.e. the list of dictionaries was empty.

As the running ibus-typing-booster reacts to this change in the dconf setting, the running ibus-typing-booster actually did work without a dictionary.

Only after “ibus restart” (or logging out and logging in again into your desktop), ibus-typing-booster restarts, finds the dictionary setting empty and then changes the empty setting to the default for the current locale.

I.e. with ibus-typing-booster 2.8.2, you can already check how it behaves without a dictionary, after deleting all dictionaries in the setup tool, it does that until the next restart or until you change the list of dictionaries in the setup tool.

I fixed that bug in 2.8.3.

**Comment by mike-fabian** [comment]
Now I wonder how I should implement support for not using a dictionary. 

When the setting in dconf for the “dictionary” or the “inputmethod” keys is empty, ibus-typing-booster cannot distinguish whether this is empty on purpose or whether it is empty because ibus-typing-booster starts for the very first time. So it assumes it is started for the very first time and replaces the empty setting with a reasonable default for the locale the user running ibus-typing-booster is using.

In case of the input methods, there is one special input method you can select in the setup tool, "NoIME” which means no input method at all, i.e. just use the keyboard layout “as is”. 

If the dconf key “inputmethod” contains “NoIME” when ibus-typing-booster starts, the setting is not empty. Therefore, apparantly this setting has been initialized before (either automatically or by the user). So this “NoIME” is used and  not replaced by a default.

Maybe I should add a similar thing to the list of dictionaries.  I.e. in addition to the dictionaries for specific languages and regions (en_US, fr_FR, ...) I could add an entry like maybe “EmptyDictionary” or “NoDictionary”. I am not sure how I should name that.

**Comment by mike-fabian** [comment]
Actually there is a way you can do that already now without introducing a special "EmptyDictionary".
You can click on the + button in the setup tool and add a dictionary which is marked as not supporting spellchecking. For example

“en 🌍 English: spellchecking ❌ Emoji ✔️”

This is marked as not supporting spellchecking because `/usr/share/myspell/en.dic` does not exist on Fedora. But the emoji data `/usr/share/unicode/cldr/common/annotations/en.xml` exists.

So this should do what you want, just choose a dictionary which has the emoji data for the language you desire but lacks the spellchecking dictionary data (the spellchecking dictionary is also used to grep for words extending what you have already typed, i.e. if there is no spellchecking dictionary, all extensions come only from your user database from stuff you typed before or the custom shortcuts you defined).

See this screenshot:

![Screenshot](https://user-images.githubusercontent.com/2330175/81948237-cefc5b00-9601-11ea-9027-b13f0c2d9652.png)

**Comment by mike-fabian** [comment]
Although what I described above does probably what you want already because `/usr/share/myspell/en.dic` does not exist on Fedora, this might not be optimal because

- it is not obvious how to do this, I also didn’t think of that possibility immediately when you asked for this feature

- `/usr/share/myspell/en.dic` may exist on distributions other than Fedora, they might package the dictionaries differently.

So maybe a special entry in the dictionary lists like “EmptyDictionary” might  be useful. I am not really sure at the moment ...

Emoji search in English is **always** possible even if you have no English dictionary setup.
For example, even if you only have the fr_FR dictionary setup in the setup tool, emoji search works both in French **and** in English. As long as `/usr/share/unicode/cldr/common/annotations/en.xml` can be found, the emoji search in English will always work, no matter which languages you configure in the setup tool, English always used as well.

**Comment by mike-fabian** [comment]
So what do you think? Is it necessary to implement anything, or is it good enough for you to choose the "en" dictionary to get only emoji and no real dictionary?

**Comment by akiross** [comment]
Ok, I'm just using it and I have a couple of remarks:

 - it is a bit hacky, as you said: it works for me, but not in general as a solution for other use cases. I could say it's fine to me, but not sure if you, as maintainer, want to keep it that way:)
 - I get a popup saying that dictionary was not found: I can still work with it, but it's not the best thing and it would be nicer to not have it.

So, in general I got the kind of interaction I was looking for, to replace Compose Key. So I'm happy :)

**Comment by mike-fabian** [comment]
>     * it is a bit hacky, as you said: it works for me, but not in general as a solution for other use cases. I could say it's fine to me, but not sure if you, as maintainer, want to keep it that way:)

What other use cases?

I am still undecided whether having a "EmptyDictionary" entry similar to "NoIME" would help or only add confusion.

I am also unsure how many people really want no dictionary.

The emoji and symbol lookup is actually quite a bit slower than the dictionary lookup, so removing the dictionary gives only a small speed improvement. It may remove clutter from the candidate list though if you only want emoji and symbols and are not interested at all in suggestions from a dictionary.

>     * I get a popup saying that dictionary was not found: I can still work with it, but it's not the best thing and it would be nicer to not have it.

I think you mean this message in the candidate list:

https://github.com/mike-fabian/ibus-typing-booster/blob/master/engine/hunspell_suggest.py#L587

I will certainly remove that message. I should have removed it a while
ago, I just forgot.  I added this long ago when the setup tool was
much simpler.  Now, when you add a language in the setup tool, you see
immediately whether a spellchecking dictionary for this language is
installed depending on whether you see the checkmark ✔️ or the ❌. This
should be enough as a hint that you might want too try installing the
dictionary (or ignore it if you don’t need the dictionary).

So I will remove that extra warning message in the candidate list.

**Comment by akiross** [comment]
> What other use cases?

Sorry, I meant other people. I don't know if somebody has other use cases.

> I am still undecided whether having a "EmptyDictionary" entry similar to "NoIME" would help or only add confusion.

Can a user add EmptyDictionary *and* another dictionary at the same time? That wouldn't be much intuitive, and the most intuitive solution would be an empty list of dictionaries. Maybe, "EmptyDictionary" could be added automatically by the setup tool when no other dictionaries are present, so user has no control over it and you still have an entry in dconf.

So, the cases could be the following:

 - No entry in dconf -> automatically add a dictionary
 - User adds dictionary -> if EmptyDictionary is present, remove it first, then add dictionary regularly
 - User removes dictionary -> if one dictionary is present, replace it with EmptyDictionary, otherwise remove it regularly

> I am also unsure how many people really want no dictionary.

IDK, but on my side I'll tell my friends that I replaced .XCompose with typing booster because it allows for more flexibility, so I guess there might be a few users interested.
If having no dictionary is something that you want in typing-booster it's up to you: maybe you think that there are better alternatives for replacing .XCompose (e.g. ibus-table, but I didn't give it a try yet). I personally think it is a feature that fits typing booster.

> The emoji and symbol lookup is actually quite a bit slower than the dictionary lookup, so removing the dictionary gives only a small speed improvement. It may remove clutter from the candidate list though if you only want emoji and symbols and are not interested at all in suggestions from a dictionary.

Yes, I noticed the speed difference with/without emoji&unicode, but reducing the clutter helps a lot in my case in how fast I can use the tool.

> So I will remove that extra warning message in the candidate list.

Thank you a lot!
After all the help you are giving me, I definitely should write a short article on how I use typing booster.

**Comment by mike-fabian** [comment]
> ... and the most intuitive solution would be an empty list of dictionaries. Maybe, "EmptyDictionary" could be added automatically by the setup tool when no other dictionaries are present, so user has no control over it and you still have an entry in dconf.

Yes, that is a good idea.

That way the user does not have to see a confusing "EmptyDictionary" entry (unless an expert user looks at the dconf key).

>     * No entry in dconf -> automatically add a dictionary

>     * User adds dictionary -> if EmptyDictionary is present, remove it first, then add dictionary regularly

>     * User removes dictionary -> if one dictionary is present, replace it with EmptyDictionary, otherwise remove it regularly

Yes, that sounds good, I’ll do that.

Currently, if you empty the dictionary list completely, you get the default for the current locale. For example, if you are running in hi_IN.UTF-8 locale and empty the dictionary list, you get the hi_IN *and* the en_GB dictionary added (In your case you got only the en_US dictionary because you run in a locale where that is the default).

When I change the behaviour of making the list empty to not using a dictionary anymore, this “reverting to the default” dictionary for the locale feature is gone. But that was not very intuitive anyway. Probably I should add buttons "Set to default" to the rows of buttons for the dictionaries and input methods, that would be much more understandable than getting the default by making the list empty.

In case of the input methods, a completely empty list makes no sense, so probably I should keep adding NoIME back if the list gets empty. Currently it goes to the default if the list gets empty, for example in hi_IN.UTF-8 locale it would add back the two input methods “hi-inscript2” and “NoIME”:

https://github.com/mike-fabian/ibus-typing-booster/blob/master/engine/itb_util.py#L264

It would probably be more intuitive if making the list empty would just add back “NoIME” and one gets “hi-inscript2” and “NoIME” only by pressing a “Set to default” button.

> IDK, but on my side I'll tell my friends that I replaced .XCompose with typing booster because it allows for more flexibility, so I guess there might be a few users interested.
> If having no dictionary is something that you want in typing-booster it's up to you: maybe you think that there are better alternatives for replacing .XCompose (e.g. ibus-table, but I didn't give it a try yet). I personally think it is a feature that fits typing booster.

I also think it is easier than to remember lots of compose sequences.
With typing booster, you usually don’t have to remember the exact
names of emoji or symbols, if you are somehow close it is already good
enough in many cases.

For some of this fuzzy matching a dictionary is needed because of the spellchecking offered by the dictionary. If you type something and a dictionary is available and the spellchecking using that dictionary finds that what you typed is not a valid word according to that dictionary, the possible spelling corrections are automatically added to the search and searched as well. See:

https://github.com/mike-fabian/ibus-typing-booster/blob/master/tests/test_emoji_candidates.py#L351

If you have no dictionary, this will not be done.

> > The emoji and symbol lookup is actually quite a bit slower than the dictionary lookup, so removing the dictionary gives only a small speed improvement. It may remove clutter from the candidate list though if you only want emoji and symbols and are not interested at all in suggestions from a dictionary.
> 
> Yes, I noticed the speed difference with/without emoji&unicode, but reducing the clutter helps a lot in my case in how fast I can use the tool.
> 
> > So I will remove that extra warning message in the candidate list.
> 
> Thank you a lot!
> After all the help you are giving me, I definitely should write a short article on how I use typing booster.

**Comment by mike-fabian** [comment]
Here is a 2.9.0 release candidate which allows to delete all dictionaries:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/

**Comment by mike-fabian** [comment]
Did you try it already? I just started another build to fix also:

https://github.com/mike-fabian/ibus-typing-booster/issues/94

**Comment by mike-fabian** [comment]
https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/build/1400883/

That build is finished now and also contains the fix for 

https://github.com/mike-fabian/ibus-typing-booster/issues/94

**Comment by mike-fabian** [comment]
The fix is included in this release:

https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.9.0

**Comment by akiross** [comment]
I tried it and it works perfectly! Thanks for your help and efforts :)
