### ISSUE TITLE
Nothing happens on 'Install missing dictionaries' 

### ISSUE THREAD

**Issue by OJFord** [mike-fabian/ibus-typing-booster#99]
First of all, thank you for this! I thought 'oh wouldn't it be great if' a while ago and then happened this repo by accident, amazing.

However, I've selected `hi_IN` (also tried `hi` global) and `en_GB`, which both had :x: spellcheck, and clicking 'Install missing dictionaries' seemed not to do anything.

When I tried to use it, it told me no dictionary was found and to please install the hunspell dictionary; so I did that manually for `en_GB`. Arch (even the AUR) doesn't have `hunspell-hi{,_IN}` though, but English & Hindi is actually an example you use in the tutorial - do you use https://github.com/Shreeshrii/hindi-hunspell? Is 'Install missing dictionaries' supposed to be able to take care of installing that for me? (I've only briefly tried to find documentation on where to put the various files, but not had much luck so far.)

Many thanks.

**Comment by mike-fabian** [comment]
This is the code to install missing dictionaries:

https://github.com/mike-fabian/ibus-typing-booster/blob/master/setup/main.py#L2756

and:

https://github.com/mike-fabian/ibus-typing-booster/blob/master/setup/pkginstall.py

I tested this on Fedora and openSUSE.

I am not sure about Arch. If it doesn’t work on Arch, I’d like to fix it of course.

Apparently you could manually install a en_GB dictionary package on Arch. And apparently it was installed into one of the directories ibus-typing-booster searches, so it works for you, if I understand you correctly.

I don’t use https://github.com/Shreeshrii/hindi-hunspell because there is a hunspell-hi package on Fedora Linux. But you can use https://github.com/Shreeshrii/hindi-hunspell if you like.

ibus-typing-booster searches for dictionaries in these directories:

https://github.com/mike-fabian/ibus-typing-booster/blob/master/engine/itb_util.py#L2843

I.e. it  first looks in `~/.local/share/ibus-typing-booster/data`, then `/usr/share/ibus-typing-booster/data`, and then in some system directories. 

So if you get the dictionaries from  https://github.com/Shreeshrii/hindi-hunspell,
you an just put the .dic and .aff files into `~/.local/share/ibus-typing-booster/data` in your home directory and it should work.

**Comment by OJFord** [comment]
Ahah, ok, thanks for the pointer. I didn't know about `packagekit`, but it seems this is a packaging issue then, the `ibus-typing-booster` package doesn't depend (even optionally) on `packagekit`.

I did eventually figure out the `*{dic,aff}` files, but I might move them to one of those directories (instead of system hunspell), thanks.
